#!/bin/bash

if [ -e /usr/lib/YaST/.configured2 ] ; then
    find /usr/lib/YaST/.configured2 -ctime +2 | xargs --no-run-if-empty -- rm -f
fi

if [ ! -e /usr/lib/YaST/.configured2 -a -w /tmp ] ; then

    test -x /etc/init.d/syslog && /etc/init.d/syslog start

    touch /usr/lib/YaST/.configured2

    for i in /usr/info/ \
             /usr/share/info/ \
             /usr/lib/info/ \
             /usr/local/info/ \
             /usr/local/lib/info/ \
             /usr/X11R6/info/ \
             /usr/X11R6/lib/info/ \
             /usr/X11R6/lib/xemacs/info/ \
             /var/adm/packages ; do
        test -d $i && touch $i 2> /dev/null
    done

    test -e /etc/rc.config && . /etc/rc.config

    echo_welcome () {

        case "$LANGUAGE" in
          german)
            echo "------------------------------------------------------------------------------"
            echo " "
            echo "                        Willkommen zu SuSE Linux"
            echo " "
          ;;
          french)
            echo "------------------------------------------------------------------------------"
            echo " "
            echo "                  SuSE Linux vous souhaite la bienvenue"
            echo " "
          ;;
          italian)
            echo "------------------------------------------------------------------------------"
            echo " "
            echo "                        Benvenuti da SuSE Linux"
            echo " "
          ;;
          *)
            echo "------------------------------------------------------------------------------"
            echo " "
            echo "                         Welcome to SuSE Linux"
            echo " "
          ;;
        esac
    }

    echo_passwd () {
        case "$LANGUAGE" in
          german)
            echo "    Als erstes sollten Sie ein Passwort für den Benutzer root vergeben. "
            echo "    Wenn Sie kein Passwort möchten, geben Sie einfach RETURN ein."
            echo " "
          ;;
          french)
            echo "    Tout d'abord, vous devriez assigner un mot de passe à l'utilisateur"
            echo "    root.  Si vous ne voulez pas de mot de passe, appuyez simplement sur"
            echo "    ENTRÉE."
            echo " "
          ;;
          italian)
            echo "    Per prima cosa dovreste assegnare una password all'utente root. "
            echo "    Se non desiderate alcuna password, premete simplicemente ENTER."
            echo " "
          ;;
          *)
            echo "    First of all, you should set a password for the root user. If you"
	    echo "    don't want a password, simply press RETURN."
            echo " "
          ;;
        esac
    }

    echo_todo () {
        case "$LANGUAGE" in
          german)
            echo "------------------------------------------------------------------------------"
            echo " "
            echo "    Vermutlich muß YaST noch einige Dinge konfigurieren, wir starten"
            echo "    einfach mal ;-)"
            echo " "
          ;;
          french)
            echo "------------------------------------------------------------------------------"
            echo " "
            echo "    YaST a probalement encore certaines choses à configurer, démarrons"
            echo "    tout simplement ;-)"
            echo " "
          ;;
          italian)
            echo "------------------------------------------------------------------------------"
            echo " "
            echo "    YaST deve probabilmente configurare ancora alcune cose, iniziamo "
            echo "    pure ;-)"
            echo " "
          ;;
          *)
            echo "------------------------------------------------------------------------------"
            echo " "
            echo "    Probably YaST still has to configure a few things, so let's just start ;-)"
            echo " "
          ;;
        esac
    }

    echo_please_wait () {
        case "$LANGUAGE" in
          german)
            echo "------------------------------------------------------------------------------"
            echo " "
            echo " Nun müssen noch einige Skripte laufen. Diese werden in etwa einer"
            echo " Minute automatisch gestartet.  Eine Logdatei finden Sie dann unter"
            echo " \"/var/log/Config.bootup\".  Außerdem können Sie die Ausgaben auf"
            echo " Console 9 beobachten."
            echo " Sie können das System jetzt bereits normal benutzen. Wenn Sie "
            echo " das System herunterfahren, bevor die Skripte beendet sind, werden "
            echo " sie beim nächsten Hochlauf nochmal gestartet."
            echo " "
          ;;
          french)
            echo "------------------------------------------------------------------------------"
            echo " "
            echo " Quelques scripts doivent encore être exécutés. Ils seront lancés "
            echo " automatiquement dans une minute environ."
            echo " Vous trouverez alors un fichier de trace sous \"/var/log/Config.bootup\"."
            echo " Vous pouvez en outre voir les affichages sur la console 9."
            echo " Vous pouvez déjà maintenant utiliser le système normalement. Si vous"
            echo " arrêtez le système avant que les scripts ne soient terminés, ils seront"
            echo " de nouveau lancés lors du prochain démarrage."
            echo " "
          ;;
          italian)
            echo "------------------------------------------------------------------------------"
            echo " "
            echo " Alcuni script devono ancora essere esecutati. Verranno automaticamente"
            echo " avviati entro un minuto circa.  Troverete allora un logfile sotto"
            echo " \"/var/log/Config.bootup\". Inoltre potete visualizzare il display sulla"
            echo " console 9."
            echo " Potete già utilizzare il sistema normalmente. Se portate giù il sistema"
            echo " prima che gli script vengano terminati, verranno di nuovo avviati la"
            echo " prossima volta che porterete su il sistema."
            echo " "
          ;;
          *)
            echo " "
            echo "------------------------------------------------------------------------------"
            echo " "
	    echo " A few scripts still have to be executed. They will be started automatically"
            echo " in 1 minute. The output will be logged in the file \"/var/log/Config.bootup\"."
	    echo " You can also find the messages on console 9, in case you want to watch."
	    echo " The system is already fully functional and ready for use!"
	    echo " In case you shut down the system before the scripts have finished, they"
	    echo " will be started again next time the system comes up."
            echo " "
          ;;
        esac
    }

    press_enter () {
        case "$LANGUAGE" in
          german)
            echo -n " Bitte <RETURN> drücken..."
          ;;
          *)
            echo -n " Press <RETURN> to continue..."
          ;;
        esac
        read < /dev/tty
    }

    echo " "
    echo " "

    echo_welcome

    echo "------------------------------------------------------------------------------"
    echo " "

    PASSWD=`grep ^root: /etc/shadow | cut -d ":" -f 2`
    if test -z "$PASSWD" ; then
        echo_passwd
        passwd
    fi

    echo " "
    echo " "

    echo_todo

    echo "------------------------------------------------------------------------------"
    echo " "

    for i in /usr/share/info /usr/man /usr/share/man /usr/X11R6/man \
             /usr/openwin/man /usr/lib/perl5/man /usr/local/man ; do
        if [ ! -e /usr/lib/YaST/.DemoMode -a -d $i ] ; then
            find $i -follow -type d 2> /dev/null | xargs touch 2> /dev/null
        fi
    done

    # there was a bug in former releases of ps.tgz - a unreadable /etc/psdevtab
    # can be there - this can be deleted. Recreate it simply with calling
    # ps as root.  This procedure speeds up ps very much...
    test -e /etc/psdevtab && rm -f /etc/psdevtab
    ps > /dev/null 2> /dev/null

    #
    # PCMCIA might be needed to install additional packages.
    # So we start cardmanager if it exists.
    #
    # ATTENTION! After finishing YaST, we need to shut down cardmanager.
    # Otherwise the system might hang when cardmanager is started on regular
    # bootup.
    #               hm, 11.06.1997

    test -x /etc/init.d/pcmcia && /etc/init.d/pcmcia start

    sleep 1
    /sbin/portmap

    # check if we are on a serial console=ttyS* and set vt102
    test -f /proc/cmdline && \
       grep -i console < /proc/cmdline > /dev/null && \
       TERM_TEMP=$(sed -e 's/^.*onsole=//' -e 's/[ ,].*$//' < /proc/cmdline)
    case $TERM_TEMP in
       ttyS*)
               TERM=vt102 /sbin/yast --nomenu
               ;;
       *)
               /sbin/yast --nomenu
               ;;
    esac

    test -x /etc/init.d/pcmcia && /etc/init.d/pcmcia stop

    echo " "
    echo " "
    echo " "
    echo " "
    clear

    /sbin/SuSEconfig -quick

    echo_please_wait

    sleep 3

    stty sane -tostop
    (
        exec 0<> /dev/null 1>&0 2>&0
        /usr/bin/setsid  /lib/YaST/bootsetup.conf
        exit 0
    ) &

    export -f press_enter
    export LANGUAGE

    rm -rf /tmp/.bootsetup$$
    if ! mkdir /tmp/.bootsetup$$ ; then
	echo "Warning - can't create /tmp/.bootsetup$$ - security problem!"
	exit 1
    fi

    ( press_enter; touch /tmp/.bootsetup$$/return ) &
    ENTER_SHELL=$!
    while [ ! -f /tmp/.bootsetup$$/return -a -f /usr/lib/YaST/.configured2 ]
    do
        sleep 1
    done
    echo
    rm -rf /tmp/.bootsetup$$
    disown $ENTER_SHELL 2>/dev/null
    kill $ENTER_SHELL 2>/dev/null

    echo " "
    echo "            Have a lot of fun!"
    echo " "
    echo " "
    echo "                              Your SuSE Team"
    echo " "
    echo " "
    echo " "

    exit 0
fi

