typedef enum _boolean {false, true} boolean;
extern void follow_all();
extern void show_all();
extern void requiresl(const char * this, ...);
extern void requiresv(const char * this, const char * requires);
extern void runlevels(const char * this, const char * lvl);
extern int makeprov(const char * name, const char * script);
extern void setorder(const char * script, const int order);
extern int getorder(const char * script);
extern boolean notincluded(const char * script, const int runlevel);
extern boolean foreach(char ** script, int * order, const int runlevel);
extern void virtprov(const char * virt, const char * real);
extern int maxorder;
