.\"
.\" Copyright 2000 Werner Fink, 2000 SuSE GmbH Nuernberg, Germany.
.\"
.\" This program is free software; you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation; either version 2 of the License, or
.\" (at your option) any later version.
.\"
.TH SHOWCONSOLE 8 "Nov 10, 2000" "Version 1.16" "The SuSE boot concept"
.UC 8
.OS SuSE Linux
.SH NAME
Showconsole \- determines the underlying tty of stdin
.SH SYNOPSIS
.\"
.B showconsole
.SH DESCRIPTION
.B showconsole
determines the underlying character device of
the current
.BR stdin.
This can be used on
.I /dev/console
as current character device to
get the real
character device back.
\."
.SH BUGS
.B showconsole
needs a mounted
.B /proc
file system and tries to set the controlling
tty to
.B stdin
if no controlling tty is found.  After reading
.B /proc
the status of the controlling tty is restored
to avoid problems with getty processes.
.SH FILES
.TP
.I /proc/<pid of showconsole>/stat
the stat file of the
.B showconsole
process.
.TP
.I /dev/console
the system console.
.\"
.SH SEE ALSO
.BR blogd  (8),
.BR console (4),
.BR tty (4),
.BR proc (5).
.SH COPYRIGHT
2000 Werner Fink,
2000 SuSE GmbH Nuernberg, Germany.
.SH AUTHOR
Werner Fink <werner@suse.de>
