.\"
.\" S.u.S.E. man page for chkstat
.\" Copyright (c) 2000 SuSE GmbH Fuerth, Germany.   
.\" please send bugfixes or comments to feedback@suse.de.
.\"
.\" Author: Ruediger Oertel        <ro@suse.de>
.\"
.TH CHKSTAT 8 "Jul 9, 1998" "Version 0.1" "Tool to check and set file permissions"
.\"
.UC 8
.SH NAME
.\"
chkstat \- Tool to check and set file permissions
.SH SYNOPSIS
.\"
.B chkstat
.RB \|[\| \-set ]
.B file-list
.\"
.SH DESCRIPTION
The perl script
.I /usr/bin/chkstat
is a tool to check and set file permissions.
.PP
.\"
.SS General Options
.TP
.IR \-set
This option enables setting the file permissions,
the default is to check and warn only.
.SH EXAMPLE
.PP
The command
.PP
.RS
.B chkstat -set /etc/permissions
.RE
.PP
will run through the complete list in /etc/permissions and set
owner,group and access mode of each file accordingly. The format
for the input file needs to be
.PP
.B FILEPATH
.B OWNER.GROUP
.B MODE
.PP
and wildcards are not supported for the filepath. Lines starting
with '#' are used as comments.
.SH COPYRIGHT
1996 SuSE GmbH Fuerth, Germany. 
.SH AUTHOR
Reinhold Sojer <reinhold@suse.de>

