.\"
.\" Copyright 2001 Werner Fink, 2001 SuSE GmbH Nuernberg, Germany.
.\"
.\" This program is free software; you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation; either version 2 of the License, or
.\" (at your option) any later version.
.\"
.TH BLOGGER  8 "Jan 26, 2001" "Version 1.16" "The SuSE boot concept"
.UC 8
.OS SuSE Linux
.SH NAME
Blogger \- writes messages to a running blogd process
.SH SYNOPSIS
.\"
.B blogger
.RB [ \-n | \-d | \-f | \-s | \-u ]
\fB"\fIa message here\fB"\fP
.SH DESCRIPTION
.B blogger
is used to send messages to the blogd process during
boot phase.  These messages will only appear in the boot
logging file
.I /var/log/boot.msg
and not on
.IR /dev/console .
.SH OPTIONS
.TP
.B \-n
Declare the following message as a
.BR <notice> .
This is the default.
.TP
.B \-d
Use thist to add the leading string
.B <done>
to the message.
.TP
.B \-f
Use thist to add the leading string
.B <failed>
to the message.
.TP
.B \-s
Use thist to add the leading string
.B <skipped>
to the message.
.TP
.B \-u
Use thist to add the leading string
.B <unused>
to the message.
.\"
.SH FILES
.TP
.I /dev/blog       
the named pipe (FIFO) used as message channel to the blogd process.
.\"
.SH SEE ALSO
.BR blogd  (8),
.BR console (4),
.BR tty (4),
.BR proc (5).
.SH COPYRIGHT
2001 Werner Fink,
2001 SuSE GmbH Nuernberg, Germany.
.SH AUTHOR
Werner Fink <werner@suse.de>
