.\"
.\" Copyright 2000 Werner Fink, 2000 SuSE GmbH Nuernberg, Germany.
.\"
.\" This program is free software; you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation; either version 2 of the License, or
.\" (at your option) any later version.
.\"
.TH BLOGD 8 "Nov 10, 2000" "Version 1.16" "The SuSE boot concept"
.UC 8
.OS SuSE Linux
.SH NAME
blogd \- boot logging on /dev/console
.SH SYNOPSIS
.\"
.B /sbin/blogd
.RI [ /dev/realtty ]
.SH DESCRIPTION
Without argument
.B blogd
determines the real underlying character device of
.IR /dev/console .
.B blogd
spawns a pty/tty pair to reconnect the current
.I /dev/console
with the slave of the pty/tty pair. During
writing information from this slave to the
real character device a ring buffer is used
to hold the information for writing it to an
.B existing
logging file.
.PP
To fetch the real tty of
.I /dev/console
the program
.BR showconsole (8)
can be used. This has the advantage that
.B blogd
will not hold the real character device of
.I /dev/console
as its controlling tty (would hangup any running
getty on that character device).
\."
.SH SIGNALS
.B blogd
knows a few signal to contol its behavior.
.TP
.BR SIGQUIT ", " SIGINT ", and " SIGTERM
will cause
.B blogd
tries to write out the ring buffer and to exit.
.TP
.B SIGIO
says
.B blogd
that now it is able to write on
.I /var/log/boot.msg
which means that the file system is
mounted read/write and the kernel
messages are written to that file.
\."
.SH BUGS
.B blogd
needs a mounted
.I /proc
and
.I /dev/pts
file system and tries to set the controlling
tty to
.B stdin
if the real character device of
.I /dev/console
is not given.  After reading
.I /proc
.B blogd
tries to restore the status of the controlling tty
to avoid problems with getty processes.  This can
fail because
.B blogd
forks to run in the background as a daemon.
.SH FILES
.TP
.I /proc/<pid of blogd>/stat
the stat file of the
.B blogd
process.
.TP
.I /dev/console
the system console.
.TP
.I /var/log/boot.msg
logging file which is created by
.BR klogd (8)
or
.BR dmesg (8).
.\"
.SH SEE ALSO
.BR showconsole (8),
.BR syslogd (8),
.BR klogd (8),
.BR dmesg (8),
.BR proc (5).
.SH COPYRIGHT
2000 Werner Fink,
2000 SuSE GmbH Nuernberg, Germany.
.SH AUTHOR
Werner Fink <werner@suse.de>
