#! /bin/bash
# Copyright (c) 2000-2002 SuSE Linux AG, Nuernberg, Germany.
# All rights reserved.
#
# Author: Petr Mladek <pmladek@suse.cz>

# will the output be the help?
SET_JAVA_PL_HELP="no"
for arg in "$@" ; do
  if [ "$arg" == "--help" ] ; then
    SET_JAVA_PL_HELP="yes"
  fi
done

if [ "$SET_JAVA_PL_HELP" = "yes" ] ; then
  # help printed, so print own help prefix
  echo "This script sets the link /usr/lib/java which defines default java for"
  echo "your computer. It sets additional links defined by the tag \"alternative\""
  echo "in configuration files located in /etc/java. It is also able set another";
  echo "compactibility links in the directory /usr/lib."
  echo
fi

exec setJava.pl --encaps setDefaultJava link "$@"
