#! /bin/bash
# Copyright (c) 2000 SuSE Gmbh Nuernberg, Germany.  All rights reserved.
#
# Author: Petr Mladek <pmladek@suse.cz>

PRINT_HELP=no
DEVEL=no

case "$#" in
  "1")
    if [ "$1" = "--help" ] ; then
      PRINT_HELP=yes
    else
      JAVA_VER=$1
    fi
    ;;
  "2")
    if [ "$1" != "--devel" ] ; then
      PRINT_HELP=yes
    else
      DEVEL=yes
      JAVA_VER=$2
    fi
    ;;
  *)
    PRINT_HELP=yes
    ;;
esac              

if [ "$PRINT_HELP" = "yes" ] ; then
  echo "This script sets default java for your computer"
  echo
  echo "Usage: setDefaultJava --help"
  echo "       setDEfaultJava [--devel] java_ver"
  echo
  echo "Command line options:"
  echo "	--help   - print this help"
  echo "	--devel  - use this options if you request the development kit"
  echo "	java_ver - is one from: SunJava1, SunJava2, IBMJava2"
  echo "                                Java2, default"
  echo "	         - SunJava1 - java ver. 1.1.x, from Sun Microsystems"
  echo "		 - SunJava2 - java ver. 1.2.x or 1.3.x, from Sun Microsystems"
  echo "		 - IBMJava2 - java ver. 1.2.x or 1.3.x, from IBM"
  echo "		 - Java2    - java ver. 1.2.x or 1.3.x, any vendor"
  echo "		 - default  - any version, any vendor"
  echo
  exit 0
fi

# check if we are started as root
# only one of UID and USER must be set correctly
if test "$UID" != 0 -a "$USER" != root; then
    echo "You must be root to start $0."
    exit 1
fi

# test if there is desired java
JAVALINKTO=

case "$JAVA_VER" in
	"SunJava1")
	  if [ "$DEVEL" = "yes" ] ; then
	    if [ -e /usr/lib/SunJava1/bin/javac ] ; then JAVALINKTO=/usr/lib/SunJava1; fi
          else    
	    if [ -d /usr/lib/SunJava1/bin ] ; then JAVALINKTO=/usr/lib/SunJava1; fi
	  fi
	  ;;
	"SunJava2")  
	  if [ "$DEVEL" = "yes" ] ; then
	    if [ -d /usr/lib/SunJava2/bin ] ; then JAVALINKTO=/usr/lib/SunJava2; fi
	  else    
	    if [ -d /usr/lib/SunJava2/jre/bin ] ; then JAVALINKTO=/usr/lib/SunJava2; fi
	  fi
	  ;;
        "IBMJava2")
	  if [ "$DEVEL" = "yes" ] ; then
	    if [ -d /usr/lib/IBMJava2/bin ] ; then JAVALINKTO=/usr/lib/IBMJava2; fi
 	  else
	    if [ -d /usr/lib/IBMJava2/jre/bin ] ; then JAVALINKTO=/usr/lib/IBMJava2; fi
	  fi
	  ;;
        "Java2")
	  if [ "$DEVEL" = "yes" ] ; then
	    if   [ -d /usr/lib/SunJava2/bin ] ; then JAVALINKTO=/usr/lib/SunJava2
	    elif [ -d /usr/lib/IBMJava2/bin ] ; then JAVALINKTO=/usr/lib/IBMJava2 
	    fi
	  else
	    if   [ -d /usr/lib/SunJava2/jre/bin ] ; then JAVALINKTO=/usr/lib/SunJava2
	    elif [ -d /usr/lib/IBMJava2/jre/bin ] ; then JAVALINKTO=/usr/lib/IBMJava2
            fi
	  fi
	  ;;
        "default")
	  if [ "$DEVEL" = "yes" ] ; then
	    if   [ -e /usr/lib/SunJava1/bin/javac ] ; then JAVALINKTO=/usr/lib/SunJava1
	    elif [ -d /usr/lib/SunJava2/bin ] ; then JAVALINKTO=/usr/lib/SunJava2
	    elif [ -d /usr/lib/IBMJava2/bin ] ; then JAVALINKTO=/usr/lib/IBMJava2
            fi
	  else
	    if   [ -d /usr/lib/SunJava1/bin ] ; then JAVALINKTO=/usr/lib/SunJava1
	    elif [ -d /usr/lib/SunJava2/jre/bin ] ; then JAVALINKTO=/usr/lib/SunJava2
	    elif [ -d /usr/lib/IBMJava2/jre/bin ] ; then JAVALINKTO=/usr/lib/IBMJava2
            fi
	  fi
          ;;
        *)	
	  echo "Error: I do not know \"$JAVA_VER\""
	  echo "       Please, use setDefaultJava --help"
	  exit 1
esac

if [ -z "$JAVALINKTO" ] ; then
  if [ "$DEVEL" = "yes" ] ; then
    echo "Error: The development version of $JAVA_VER is not installed"
  else
    echo "Error: The requested $JAVA_VER is not installed"
  fi
  exit 1
fi

# create requested link
if [ -L /usr/lib/java ] ; then rm /usr/lib/java; fi
ln -sf `linkto $JAVALINKTO` /usr/lib/java
exit 0
