#!/bin/bash
# Copyright (c) 2000-2002 SuSE Linux AG, Nuernberg, Germany.
# All rights reserved.
#
# Author: Sonja Krause-Harder <skh@suse.de> 

echo -e \
'################################################################\n'\
'# setDefaultJava is no longer supported. Please install the    #\n'\
'# package jpackage-utils and read the documentation in         #\n'\
'# /usr/share/doc/packages/jpackage-utils for information about #\n'\
'# the new java packages on SUSE Linux.                         #\n'\
'################################################################'

