#!/bin/sh
#
#
# backup_rpmdb
#
# Copyright (c) 1996-2002 SuSE Linux AG, Nuernberg, Germany.
# Copyright (c) 2018 SUSE Linux GmbH, Nuernberg, Germany.
#
# Author: Burchard Steinbild, 1996
#         Florian La Roche, 1996
#
# paranoia settings
#
umask 022

PATH=/sbin:/bin:/usr/sbin:/usr/bin
export PATH

RPMDB_PATH="/usr/lib/sysimage/rpm"

#
# get information from /etc/sysconfig
#
if [ -f /etc/sysconfig/backup ] ; then
    . /etc/sysconfig/backup
fi
#
#
PACKAGEDBFILE=packages.rpm
if test -e ${RPMDB_PATH}/Packages ; then
    PACKAGEDBFILE=Packages
fi
#
# create backups of rpm data base
#
if test -n "$RPMDB_BACKUP_DIR" -a -e ${RPMDB_PATH}/$PACKAGEDBFILE ; then
    mkdir -p $RPMDB_BACKUP_DIR
    OLD_MD5=""
    test -e $RPMDB_BACKUP_DIR/rpmdb_recent_md5 && \
        OLD_MD5="`cat $RPMDB_BACKUP_DIR/rpmdb_recent_md5`"
    NEW_MD5="`cat ${RPMDB_PATH}/$PACKAGEDBFILE | md5sum`"
    if test "$OLD_MD5" != "$NEW_MD5" ; then
        if ! rpm -qa > /dev/null 2>&1  ; then
            echo "ERROR!! something wrong with RPM DB, it might be corrupted, please double check"
            logger -p cron.err "ERROR!! something wrong with RPM DB, it might be corrupted, please double check"
            exit 1
        fi
        DATESTRING=`date +"%Y%m%d"`

        NEWNAME=$RPMDB_BACKUP_DIR/$PACKAGEDBFILE-$DATESTRING
        NUMBER=2
        while [ -e $NEWNAME -o -e $NEWNAME.gz ] ; do
            NEWNAME=$RPMDB_BACKUP_DIR/$PACKAGEDBFILE-$DATESTRING-$NUMBER
            NUMBER=`expr $NUMBER + 1`
        done

        if gzip -9 < ${RPMDB_PATH}/$PACKAGEDBFILE > $NEWNAME.gz; then
            echo "$NEW_MD5" > $RPMDB_BACKUP_DIR/rpmdb_recent_md5
            test "$MAX_RPMDB_BACKUPS" -gt 0 2> /dev/null || MAX_RPMDB_BACKUPS=0
            NUMBER=1
            for BACKUPFILE in `ls -1 -t $RPMDB_BACKUP_DIR/$PACKAGEDBFILE-*` ; do
                if test "$NUMBER" -gt "$MAX_RPMDB_BACKUPS" ; then
                    rm -f $BACKUPFILE
                fi
                NUMBER=`expr $NUMBER + 1`
            done
        else
            echo "ERROR!! can not backup RPM Database to $RPMDB_BACKUP_DIR."
            echo "Maybe there is not enough disk space."
            rm -f $NEWNAME $NEWNAME.gz
        fi
    fi
fi

exit 0
