#!/bin/sh
#
#
# clean_instlog. This script was split off cron.daily.
# Please add your local changes to cron.daily.local
# since this file will be overwritten, when updating your system.
#
# Copyright (c) 1996-2000 SuSE GmbH Nuernberg, Germany.   
#
# please send bugfixes or comments to feedback@suse.de.
#
# Author: Burchard Steinbild <bs@suse.de>, 1996
#         Florian La Roche <florian@suse.de>, 1996
#


#
# paranoia settings
#
umask 022

PATH=/sbin:/bin:/usr/sbin:/usr/bin
export PATH

#
# get information from /etc/rc.config
#
if [ -f /etc/rc.config ] ; then
    . /etc/rc.config
fi

#
# look for old YaST log files
#
test "$MAX_DAYS_FOR_LOG_FILES" -gt 0 2> /dev/null || MAX_DAYS_FOR_LOG_FILES=0
export MAX_DAYS_FOR_LOG_FILES

if test $MAX_DAYS_FOR_LOG_FILES -gt 0 ; then
    find /var/adm/inst-log/ -name "installation-*" -ctime +90 \
        -type f \! -name "*.gz" -print0 2> /dev/null | \
        xargs --no-run-if-empty --max-lines=200 --null -- gzip -9
    find /var/adm/inst-log/ -name "installation-*.gz" \
        -mtime +$MAX_DAYS_FOR_LOG_FILES \
        -type f -print0 2> /dev/null | \
        xargs --no-run-if-empty --max-lines=200 --null -- rm -f
fi

exit 0
