.\"
.\" SuSE man page route.conf
.\" Copyright (c) 2002 SuSE Linux AG, Nuernberg, Germany.
.\" please send bugfixes or comments to feedback@suse.de.
.\"
.\"
.TH ROUTE.CONF 5 "March 13th, 2002" "Version 0.0" "Configuration for routing table"
.\"
.UC 5
.SH NAME
.\"
route.conf \- Configuration for routing table has
.B changed
.SH SYNOPSIS
.\"
.B /etc/route.conf -> /etc/sysconfig/network/routes
.\"
.SH DESCRIPTION
The file
.I /etc/route.conf
is no longer used starting with versions SuSE Linux 8.0. Please see 
.I routes(5)
for the routing configuration. To do so issue
.PP
.RS
.B $ man routes
.SH SEE ALSO
.BR routes (5),
.SH COPYRIGHT
2002 SuSE Linux AG, Nuernberg, Germany.
.SH AUTHOR
Mads Martin Jørgensen <mmj@suse.de>
