.\" Copyright (C) 2003 SuSE Linux AG
.\"$Id:$
.TH quick_halt 8
.SH NAME
quick_halt \- stop the system quickly
.SH SYNOPSIS
\fBquick_halt\fR, \fBquick_reboot\fR, \fBquick_poweroff\fR
.SH DESCRIPTION
Fast system shutdown, that does not carefully stop every single service
in the specified order, but just sends a TERM and KILL to everyone
and makes sure the filesystems get shut down properly prior to
reboot/halt/poweroff
.SH DIAGNOSTICS
If you're not the superuser,  you  will  get  the  message
"You need to be root to execute quick_halt".
.BR 
.SH "SEE ALSO"
.BR \fBshutdown\fR(8), \fBinit\fR(1), \fBhalt\fR(8), \fBpoweroff\fR(8), \fBreboot\fR(8), \fBfsck\fR(8)
.SH AUTHOR
Kurt Garloff <garloff@suse.de>
.BR 
