.\" Copyright (C) 2003 SuSE Linux AG
.\"$Id:$
.TH safe\-rm(dir) 8
.SH NAME
safe\-rm \- delete files a bit more safely
.br
safe\-rmdir \- delete empty directories a bit more safely
.SH SYNOPSIS
\fBsafe\-rm\fR \fI/path/to/file\fR
.br
\fBsafe\-rmdir\fR \fI/path/to/directory\fR
.SH DESCRIPTION
.TP
\fBsafe\-rm\fR deletes files specified with an absolute path
name. Files specified with symbolic links in the
path name will not be erased.
.TP
\fBsafe\-rmdir\fR deletes directories specified with an absolute
path name. Directories specified with symbolic links in the
path name will not be erased.
.SH RETURNS
\fBsafe\-rm\fR and \fBsafe\-rmdir\fR returns a non zero return code
when it can not erase the file safely.
.br
.SH NOTE
These commands are used by the system cleanup cron jobs.
.br
.SH "SEE ALSO"
.BR rm (1),
.BR rmdir (1).
.SH AUTHOR
SuSE Linux AG
