.TH service 8 "Sep 2014"
.SH NAME
service \- run service
.SH SYNOPSIS
       service \fBSERVICE\fR \fBACTION\fR [\fBOPTIONS\fR]
.br
       service --status-all
.br
       service --help | -h

.SH DESCRIPTION
.PP
The \fBSERVICE\fR parameter specifies a systemd service name to operate on.
The supported values of \fBACTION\fR depend  on  the specified  service.
The actions start, stop, reload, restart, try-restart, force-reload, and status
are forwarded to systemctl, \fBOPTIONS\fR are ignored in that case.

The \-\-status-all option displays the status of all loaded service units.

.SH HISTORY
service used to run System V init scripts in a predictable environment.

.SH USE AS rc* WRAPPER
SUSE Linux distributions used to have convenience symlinks to call
System V init scripts, for example /usr/sbin/rcexample ->
/etc/init.d/example. With the move to systemd the service command
can be used as wrapper for systemctl instead. For example
/usr/sbin/rcexample -> /usr/sbin/service.

.BR 
.SH "SEE ALSO"
chkconfig(8),
systemctl(1)
systemd.service(5)
.BR 
