#! /bin/sh
# Copyright (c) 1996,98 SuSE GmbH Nuernberg, Germany.  All rights reserved.
#
# Author: Burchard Steinbild <bs@suse.de>, 1996-97
#         Florian La Roche <florian@suse.de>, 1996
# i18n support added by Aleksey Smirnov <smi@logic.ru>
#  & Aleksey Novodvorsky <aen@logic.ru> from IPLabs Linux Team, Moscow.
# Attention! The shell must be restarted before localisation takes effect!
#

echo "Started the SuSE-Configuration Tool."

# check if we are started as root
# only one of UID and USER must be set correctly
if test "$UID" != "0" -a "$USER" != root -a -z "$ROOT" ; then
    echo "You must be root to start $0."
    exit 1
fi

r=$ROOT


FASTRUN=false
export FASTRUN
CHECK_NEWPACKAGE=true
export CHECK_NEWPACKAGE
FORCE_REPLACE=false
export FORCE_REPLACE
VERBOSE=false
export VERBOSE

for i in $* ; do
  case $i in
    *-verbose)
      VERBOSE=true
      echo Running in verbose mode.
    ;;
    *-quick)
      FASTRUN=true
      echo Running in quick mode.
    ;;
    *-nonewpackage)
      CHECK_NEWPACKAGE=false
      echo Skipping new package checks.
    ;;
    *-force)
      FORCE_REPLACE=true
    ;;
    *)
      echo Unknown parameter $i.
      echo Usage: SuSEconfig "[--quick|--nonewpackage|--force|--verbose]"
      exit 1
    ;;
  esac
done

test "$FASTRUN" = false -a "$CHECK_NEWPACKAGE" = true && \
    echo Running in full featured mode.

#
# where can SuSEconfig store data in running system?
#
LIBDIR=$r/var/adm/SuSEconfig

#
# LASTRUN and OLDHOSTENTRY must be a file name placed in LIBDIR
#
LASTRUN=$LIBDIR/lastrun
IS_RUNNING=$r/var/lock/SuSEconfig-is-running
MD5DIR=$LIBDIR/md5
export MD5DIR
OLDHOSTENTRY=$LIBDIR/oldhostentry

test -f $r/lib/YaST/SuSEconfig.functions || {
    echo "ERROR - can not find $r/lib/YaST/SuSEconfig.functions!!"
    echo "This should not happen.  Exit..."
    exit 1
}

. $r/lib/YaST/SuSEconfig.functions

echo "Reading $r/etc/rc.config and updating the system..."

if test ! -f $r/etc/rc.config ; then
    echo "No $r/etc/rc.config found." 
    exit 1 
fi

. $r/etc/rc.config

if test -n "$ENABLE_SUSECONFIG" -a "$ENABLE_SUSECONFIG" = "no" ; then
    echo "SuSEconfig is disabled in $r/etc/rc.config. Exit..."
    exit 0
fi

# rc.config sets a new PATH
if test "$r" != ""; then
        PATH=$PATH:$r/bin:$r/usr/bin:$r/sbin:$r/usr/sbin
        export PATH
fi

#
# first of all test if we have space.  If not abort.
#
for DIR in $r/etc $r/usr/lib/irc $r/var/lib/news ; do
    my_test_write $DIR || continue
    dd if=/dev/zero of=$DIR/testforspace.SuSEconfig bs=1k count=50 \
        2> /dev/null  || {
        rm -f $DIR/testforspace.SuSEconfig
        echo
        echo
        echo We do not have enough disk space in $DIR. Exit.
        echo
        exit 1
    }
    rm -f $DIR/testforspace.SuSEconfig
done


#
# now make sure, that LIBDIR exists
#
test -e $LIBDIR || mkdir -p $LIBDIR

#
# delete very old lock files
#

if test -x /usr/bin/find -a -x /usr/bin/xargs ; then
    /usr/bin/find $IS_RUNNING -cmin +1000 2> /dev/null \
    | /usr/bin/xargs --no-run-if-empty rm -f
fi

#
# check locking
#

if test -e $IS_RUNNING ; then
    echo -n "Another SuSEconfig seems to run.  Waiting up to 60 seconds"
    for i in 1 2 3 4 5 6 7 8 9 0 ; do
        for j in 1 2 3 4 5 6 ; do
            echo -n .
            sleep 1
            test -e $IS_RUNNING || break
        done
        test -e $IS_RUNNING || break
    done
    if test -e $IS_RUNNING ; then
        echo
        echo
        echo "Giving up..."
        echo
        echo "ps a | grep SuSEconfig"
        ps a | grep SuSEconfig
        echo
        echo "If You think, there is no other SuSEconfig running, please call"
        echo
        echo "    rm $IS_RUNNING "  
        echo
        echo "Then you can start SuSEconfig again."
        echo
        exit 1
    fi
    echo
fi

echo $$ > $IS_RUNNING

if test -n "$FQHOSTNAME" -a "$CHECK_ETC_HOSTS" = "yes" ; then
    #
    # maybe there was another name or IP Adress before. When it has been
    # changed, this could lead into trouble, if it stays in /etc/hosts.
    #
    if test -e $OLDHOSTENTRY ; then
        for OLDENTRY in `cat $OLDHOSTENTRY` ; do
            cat $r/etc/hosts | grep -vw "$OLDENTRY" > $r/etc/hosts.wrzl
            cp -p $r/etc/hosts.wrzl $r/etc/hosts
            rm -f $r/etc/hosts.wrzl
        done
        rm -f $OLDHOSTENTRY
    fi

    #
    # check, if we have localhost defined...
    #
    grep localhost $r/etc/hosts > /dev/null 2>&1
    if test $? -eq 1 ; then
        echo "127.0.0.1       localhost" >> $r/etc/hosts
    fi

    echo $FQHOSTNAME >> $OLDHOSTENTRY
    NICKNAME=`echo $FQHOSTNAME | sed -e"s:\..*::"`
    echo $NICKNAME > $r/etc/HOSTNAME.SuSEconfig
    check_md5_and_move $r/etc/HOSTNAME

    NET_DEVICE_FOUND=false

    if test -n "$NETCONFIG" -a "$NETCONFIG" != "YAST_ASK" ; then
        for I in $NETCONFIG ; do
            eval IPADDR=\$IPADDR$I
            if test -n "$IPADDR" ; then
                test -x /usr/bin/cut && \
                    IPADDR=`echo "$IPADDR              " | /usr/bin/cut -c -15`
                grep -w ${IPADDR} $r/etc/hosts > /dev/null || \
                    echo "$IPADDR	$FQHOSTNAME 	$NICKNAME" >> $r/etc/hosts
                echo "$IPADDR" >> $OLDHOSTENTRY
                NET_DEVICE_FOUND=true
            fi
        done
    fi

    # to get plp to work, we have to add hostname to localhost.
    if test "$NET_DEVICE_FOUND" = false -a "$NETCONFIG" != "YAST_ASK" ; then
        grep -vw $FQHOSTNAME $r/etc/hosts > $r/etc/hosts.tmp
        echo "127.0.0.2      	$FQHOSTNAME 	$NICKNAME" >> $r/etc/hosts.tmp
        cp -p $r/etc/hosts.tmp $r/etc/hosts
        rm -f $r/etc/hosts.tmp
    fi

    #
    # now beautify /etc/hosts
    #
    if test "$BEAUTIFY_ETC_HOSTS" = yes ; then
        grep "^#" $r/etc/hosts > $r/etc/hosts.wrzl
        echo >> $r/etc/hosts.wrzl
        echo >> $r/etc/hosts.wrzl
        grep -v "^#" $r/etc/hosts | grep -v "^\$" | sort >> $r/etc/hosts.wrzl
        mv $r/etc/hosts.wrzl $r/etc/hosts
    fi
fi


if test -n "$CREATE_RESOLVCONF" -a "$CREATE_RESOLVCONF" = "yes" -a \
    "$DHCLIENT" != yes ; then
    if test -z "$SEARCHLIST" -a -z "$NAMESERVER" ; then
        # user wants no DNS - delete it.
        rm -f $r/etc/resolv.conf
    else
        echo_warning /etc/resolv.conf \
             "# Change variables (NAMESERVER + SEARCHLIST) in /etc/rc.config instead." \
            > $r/etc/resolv.conf.SuSEconfig
    
        test -n "$SEARCHLIST" && echo -e "search $SEARCHLIST" >> $r/etc/resolv.conf.SuSEconfig
        for NSIP in $NAMESERVER; do
            echo -e "nameserver $NSIP" >> $r/etc/resolv.conf.SuSEconfig
        done
        check_md5_and_move $r/etc/resolv.conf
    fi
fi


if test -n "$CREATE_HOSTCONF" -a "$CREATE_HOSTCONF" = "yes" ; then
    echo_warning /etc/host.conf.SuSEconfig \
        "# Change variables (NAMESERVER + YP_SERVER) in /etc/rc.config instead." \
        > $r/etc/host.conf.SuSEconfig

    if test -n "$NAMESERVER" ; then
        if test "$USE_NIS_FOR_RESOLVING" = yes ; then
            echo "order hosts nis bind" >> $r/etc/host.conf.SuSEconfig
        else
            echo "order hosts bind" >> $r/etc/host.conf.SuSEconfig
        fi
    else
        if test "$USE_NIS_FOR_RESOLVING" = yes ; then
            echo "order hosts nis" >> $r/etc/host.conf.SuSEconfig
        else
            echo "order hosts" >> $r/etc/host.conf.SuSEconfig
        fi
    fi
    echo "multi on" >> $r/etc/host.conf.SuSEconfig
    check_md5_and_move $r/etc/host.conf
fi

test -n "$ORGANIZATION" && {
    echo "$ORGANIZATION" > $r/etc/organization.SuSEconfig
    check_md5_and_move $r/etc/organization
}

test -n "$NNTPSERVER" && {
    echo "$NNTPSERVER" > $r/etc/nntpserver.SuSEconfig
    check_md5_and_move $r/etc/nntpserver
}

test -n "$FROM_HEADER" && {
    echo "$FROM_HEADER" > $r/etc/inews_mail_gateway.SuSEconfig
    check_md5_and_move $r/etc/inews_mail_gateway
}

if test -n "$IRCSERVER" ; then
    if my_test_write $r/usr/lib/irc; then
        (for i in $IRCSERVER; do
                echo $i
        done) > $r/usr/lib/irc/ircII.servers.SuSEconfig
        check_md5_and_move $r/usr/lib/irc/ircII.servers
    fi
fi

if test -n "$TIMEZONE" -a "$TIMEZONE" != "YAST_ASK" -a -x /usr/sbin/zic ; then
    /usr/sbin/zic -l $TIMEZONE
fi

if test -n "$MOUSE" -a "$MOUSE" != "YAST_ASK" ; then
    rm -f $r/dev/mouse
    ln -sf $MOUSE $r/dev/mouse
fi
if test -n "$MODEM" -a "$MODEM" != "YAST_ASK" ; then
    rm -f $r/dev/modem
    ln -sf $MODEM $r/dev/modem
fi

if test ! -e /sbin/conf.d/SuSEconfig.sendmail -a \
    "$SENDMAIL_TYPE" != no -a "$SENDMAIL_TYPE" != "YAST_ASK" ; then
        SENDMAIL_FILE=$r/etc/sendmail.smtp.cf
        if test "$SENDMAIL_TYPE" = uucp-only; then
                SENDMAIL_FILE=$r/etc/sendmail.uucp.cf
        fi
        test -e $SENDMAIL_FILE && \
        sed -e "s/^DS.*\$/DS${SENDMAIL_SMARTHOST}/" \
                -e "s/^Cw.*\$/Cw${SENDMAIL_LOCALHOST}/" \
                -e "s/^DR.*\$/DR${SENDMAIL_RELAY}/" \
                -e "s/^DH.*\$/DH${SENDMAIL_RELAY}/" \
                -e "s/^DM.*\$/DM${FROM_HEADER}/" \
                < $SENDMAIL_FILE > $r/etc/sendmail.cf.SuSEconfig
        test -e $SENDMAIL_FILE && check_md5_and_move $r/etc/sendmail.cf
fi


if test -n "$FROM_HEADER" -a -d $r/var/lib/news/ ; then
    echo "$FROM_HEADER" > $r/var/lib/news/mailname.SuSEconfig
    check_md5_and_move $r/var/lib/news/mailname
    echo "$FROM_HEADER" > $r/var/lib/news/whoami.SuSEconfig
    check_md5_and_move $r/var/lib/news/whoami
fi

#
# Now setup /etc/SuSEconfig stuff
#
mkdir -p $r/etc/SuSEconfig
echo_warning /etc/SuSEconfig/profile \
        "# Change variables in /etc/rc.config instead." \
        > $r/etc/SuSEconfig/profile.SuSEconfig
echo_warning /etc/SuSEconfig/csh.login \
        "# Change variables in /etc/rc.config instead." \
        > $r/etc/SuSEconfig/csh.login.SuSEconfig
echo_warning /etc/SuSEconfig/csh.cshrc \
        "# Change variables in /etc/rc.config instead." \
        > $r/etc/SuSEconfig/csh.cshrc.SuSEconfig

if test "$CWD_IN_ROOT_PATH" = "yes" ; then
    echo "test \"\$UID\" = 0 && PATH=\"\$PATH:.\"" \
        >> $r/etc/SuSEconfig/profile.SuSEconfig
    echo "if ( \"\$uid\" == \"0\" ) set path=( \$path . )" \
        >> $r/etc/SuSEconfig/csh.login.SuSEconfig
fi

#The following lines are to be changed (IPLabs)
#if test "$LANGUAGE" = "german" ; then
#    echo "LC_CTYPE=de_DE" >> $r/etc/SuSEconfig/profile.SuSEconfig
#    echo "export LC_CTYPE" >> $r/etc/SuSEconfig/profile.SuSEconfig
#    echo "setenv LC_CTYPE de_DE" >> $r/etc/SuSEconfig/csh.cshrc.SuSEconfig
#else
#    echo "LC_CTYPE=en_GB" >> $r/etc/SuSEconfig/profile.SuSEconfig
#    echo "export LC_CTYPE" >> $r/etc/SuSEconfig/profile.SuSEconfig
#    echo "setenv LC_CTYPE en_GB" >> $r/etc/SuSEconfig/csh.cshrc.SuSEconfig
#fi

#added by IPLabs
case "$LANGUAGE" in
        german)
#           echo "LC_CTYPE=de_DE" >> $r/etc/SuSEconfig/profile.SuSEconfig
#           echo "export LC_CTYPE" >> $r/etc/SuSEconfig/profile.SuSEconfig   
#           echo "setenv LC_CTYPE de_DE" >> $r/etc/SuSEconfig/csh.cshrc.SuSEconfig
            echo "LANG=de_DE" >> $r/etc/SuSEconfig/profile.SuSEconfig
            echo "export LANG" >> $r/etc/SuSEconfig/profile.SuSEconfig
            echo "setenv LANG de_DE" >> $r/etc/SuSEconfig/csh.cshrc.SuSEconfig

        ;;
        russian)
           ln -sf /usr/share/locale/ru_SU /usr/share/locale/ru_RU.KOI8-R
#           echo "LC_CTYPE=ru_RU.KOI8-R" >> $r/etc/SuSEconfig/profile.SuSEconfig
#           echo "export LC_CTYPE" >> $r/etc/SuSEconfig/profile.SuSEconfig
           echo "LANG=ru_RU.KOI8-R" >> $r/etc/SuSEconfig/profile.SuSEconfig
           echo "export LANG" >> $r/etc/SuSEconfig/profile.SuSEconfig
#           echo "setenv LC_CTYPE ru_RU.KOI8-R" >> $r/etc/SuSEconfig/csh.cshrc.SuSEconfig
           echo "setenv LANG ru_RU.KOI8-R" >> $r/etc/SuSEconfig/csh.cshrc.SuSEconfig
        ;;

        brazilian)
           echo "LANG=pt_BR" >> $r/etc/SuSEconfig/profile.SuSEconfig
           echo "export LANG" >> $r/etc/SuSEconfig/profile.SuSEconfig  
           echo "setenv LANG pt_BR" >> $r/etc/SuSEconfig/csh.cshrc.SuSEconfig
        ;;

        czech)
           echo "LANG=cs_CZ" >> $r/etc/SuSEconfig/profile.SuSEconfig
           echo "export LANG" >> $r/etc/SuSEconfig/profile.SuSEconfig  
           echo "setenv LANG cs_CZ" >> $r/etc/SuSEconfig/csh.cshrc.SuSEconfig
        ;;

        danish)
           echo "LANG=da_DK" >> $r/etc/SuSEconfig/profile.SuSEconfig
           echo "export LANG" >> $r/etc/SuSEconfig/profile.SuSEconfig  
           echo "setenv LANG da_DK" >> $r/etc/SuSEconfig/csh.cshrc.SuSEconfig
        ;;

        dutch)
           echo "LANG=nl_NL" >> $r/etc/SuSEconfig/profile.SuSEconfig
           echo "export LANG" >> $r/etc/SuSEconfig/profile.SuSEconfig  
           echo "setenv LANG nl_NL" >> $r/etc/SuSEconfig/csh.cshrc.SuSEconfig
        ;;

        english)
           echo "LANG=en_GB" >> $r/etc/SuSEconfig/profile.SuSEconfig
           echo "export LANG" >> $r/etc/SuSEconfig/profile.SuSEconfig
           echo "setenv LANG en_GB" >> $r/etc/SuSEconfig/csh.cshrc.SuSEconfig
        ;;

        french)
           echo "LANG=fr_FR" >> $r/etc/SuSEconfig/profile.SuSEconfig
           echo "export LANG" >> $r/etc/SuSEconfig/profile.SuSEconfig  
           echo "setenv LANG fr_FR" >> $r/etc/SuSEconfig/csh.cshrc.SuSEconfig
        ;;
        greek)
           ln -sf /usr/share/locale/gr_GR /usr/share/locale/el_GR
           echo "LANG=el_GR" >> $r/etc/SuSEconfig/profile.SuSEconfig
           echo "export LANG" >> $r/etc/SuSEconfig/profile.SuSEconfig
           echo "setenv LANG el_GR" >> $r/etc/SuSEconfig/csh.cshrc.SuSEconfig
        ;;
        hungarian)
           echo "LANG=hu_HU" >> $r/etc/SuSEconfig/profile.SuSEconfig
           echo "export LANG" >> $r/etc/SuSEconfig/profile.SuSEconfig
           echo "setenv LANG hu_HU" >> $r/etc/SuSEconfig/csh.cshrc.SuSEconfig
        ;;
        indonesian)
           echo "LANG=id_ID" >> $r/etc/SuSEconfig/profile.SuSEconfig
           echo "export LANG" >> $r/etc/SuSEconfig/profile.SuSEconfig
           echo "setenv LANG id_ID" >> $r/etc/SuSEconfig/csh.cshrc.SuSEconfig
        ;;
        italian)
           echo "LANG=it_IT" >> $r/etc/SuSEconfig/profile.SuSEconfig
           echo "export LANG" >> $r/etc/SuSEconfig/profile.SuSEconfig
           echo "setenv LANG it_IT" >> $r/etc/SuSEconfig/csh.cshrc.SuSEconfig
        ;;
        polish)
           echo "LANG=pl_PL" >> $r/etc/SuSEconfig/profile.SuSEconfig
           echo "export LANG" >> $r/etc/SuSEconfig/profile.SuSEconfig
           echo "setenv LANG pl_PL" >> $r/etc/SuSEconfig/csh.cshrc.SuSEconfig
        ;;
        portuguese)
           echo "LANG=pt_PT" >> $r/etc/SuSEconfig/profile.SuSEconfig
           echo "export LANG" >> $r/etc/SuSEconfig/profile.SuSEconfig
           echo "setenv LANG pt_PT" >> $r/etc/SuSEconfig/csh.cshrc.SuSEconfig
        ;;

        romanian)
           echo "LANG=ro_RO" >> $r/etc/SuSEconfig/profile.SuSEconfig
           echo "export LANG" >> $r/etc/SuSEconfig/profile.SuSEconfig
           echo "setenv LANG ro_RO" >> $r/etc/SuSEconfig/csh.cshrc.SuSEconfig
        ;;

        slovak)
           echo "LANG=sk_SK" >> $r/etc/SuSEconfig/profile.SuSEconfig
           echo "export LANG" >> $r/etc/SuSEconfig/profile.SuSEconfig
           echo "setenv LANG sk_SK" >> $r/etc/SuSEconfig/csh.cshrc.SuSEconfig
        ;;
        spanish)
           echo "LANG=es_ES" >> $r/etc/SuSEconfig/profile.SuSEconfig
           echo "export LANG" >> $r/etc/SuSEconfig/profile.SuSEconfig
           echo "setenv LANG es_ES" >> $r/etc/SuSEconfig/csh.cshrc.SuSEconfig
        ;;
        turkish)
           echo "LANG=tr_TR" >> $r/etc/SuSEconfig/profile.SuSEconfig
           echo "export LANG" >> $r/etc/SuSEconfig/profile.SuSEconfig
           echo "setenv LANG tr_TR" >> $r/etc/SuSEconfig/csh.cshrc.SuSEconfig
        ;;

        *)
           echo "LANG=POSIX" >> $r/etc/SuSEconfig/profile.SuSEconfig
           echo "export LANG" >> $r/etc/SuSEconfig/profile.SuSEconfig
           echo "setenv LANG POSIX" >> $r/etc/SuSEconfig/csh.cshrc.SuSEconfig
        ;;

esac
export LANG=$LANGUAGE
# end of i18n support

if test -n "$FROM_HEADER" ; then
    echo "FROM_HEADER=\"$FROM_HEADER\"" >> $r/etc/SuSEconfig/profile.SuSEconfig
    echo "export FROM_HEADER" >> $r/etc/SuSEconfig/profile.SuSEconfig
    echo "setenv FROM_HEADER \"$FROM_HEADER\"" >> $r/etc/SuSEconfig/csh.cshrc.SuSEconfig
fi
if test -n "$SCANNER_TYPE" ; then
    echo "SCANNER_TYPE=$SCANNER_TYPE" >> $r/etc/SuSEconfig/profile.SuSEconfig
    echo "export SCANNER_TYPE" >> $r/etc/SuSEconfig/profile.SuSEconfig
    echo "setenv SCANNER_TYPE $SCANNER_TYPE" >> $r/etc/SuSEconfig/csh.cshrc.SuSEconfig
fi
if test -n "$DOC_HOST" ; then
    echo "SUSE_DOC_HOST=$DOC_HOST" >> $r/etc/SuSEconfig/profile.SuSEconfig
    echo "export SUSE_DOC_HOST" >> $r/etc/SuSEconfig/profile.SuSEconfig
    echo "setenv SUSE_DOC_HOST $DOC_HOST" >> $r/etc/SuSEconfig/csh.cshrc.SuSEconfig
fi
if test -d $r/opt/kde ; then
    echo "KDEDIR=/opt/kde" >> $r/etc/SuSEconfig/profile.SuSEconfig
    echo "export KDEDIR" >> $r/etc/SuSEconfig/profile.SuSEconfig
    echo "setenv KDEDIR /opt/kde" >> $r/etc/SuSEconfig/csh.cshrc.SuSEconfig
fi
if test -d $r/usr/X11R6/lib/qt ; then
    echo "QTDIR=/usr/X11R6/lib/qt" >> $r/etc/SuSEconfig/profile.SuSEconfig
    echo "export QTDIR" >> $r/etc/SuSEconfig/profile.SuSEconfig
    echo "setenv QTDIR /usr/X11R6/lib/qt" >> $r/etc/SuSEconfig/csh.cshrc.SuSEconfig
fi
if test -d $r/usr/lib/qt ; then
    echo "QTDIR=/usr/lib/qt" >> $r/etc/SuSEconfig/profile.SuSEconfig
    echo "export QTDIR" >> $r/etc/SuSEconfig/profile.SuSEconfig
    echo "setenv QTDIR /usr/lib/qt" >> $r/etc/SuSEconfig/csh.cshrc.SuSEconfig
fi
if test -d $r/opt/gnome ; then
    echo "GNOMEDIR=/opt/gnome" >> $r/etc/SuSEconfig/profile.SuSEconfig
    echo "export GNOMEDIR" >> $r/etc/SuSEconfig/profile.SuSEconfig
    echo "setenv GNOMEDIR /opt/gnome" >> $r/etc/SuSEconfig/csh.cshrc.SuSEconfig
fi
if test -d $r/usr/X11R6/lib/xad ; then
    echo "XADIDIR=/usr/X11R6/lib/xad" >> $r/etc/SuSEconfig/profile.SuSEconfig
    echo "export XADIDIR" >> $r/etc/SuSEconfig/profile.SuSEconfig
    echo "setenv XADIDIR /usr/X11R6/lib/xad" >> $r/etc/SuSEconfig/csh.cshrc.SuSEconfig
fi
if test -d $r/usr/lib/dvgt_help ; then
    echo "DV_IMMED_HELP=/usr/lib/dvgt_help" >> $r/etc/SuSEconfig/profile.SuSEconfig
    echo "export DV_IMMED_HELP" >> $r/etc/SuSEconfig/profile.SuSEconfig
    echo "setenv DV_IMMED_HELP /usr/lib/dvgt_help" >> $r/etc/SuSEconfig/csh.cshrc.SuSEconfig
fi
if test -d $r/usr/lib/maple ; then
    echo "MAPLE=/usr/lib/maple" >> $r/etc/SuSEconfig/profile.SuSEconfig
    echo "export MAPLE" >> $r/etc/SuSEconfig/profile.SuSEconfig
    echo "setenv MAPLE /usr/lib/maple" >> $r/etc/SuSEconfig/csh.cshrc.SuSEconfig
fi
if test -d $r/usr/lib/rasmol ; then
    echo "RASMOLPATH=/usr/lib/rasmol" >> $r/etc/SuSEconfig/profile.SuSEconfig
    echo "export RASMOLPATH" >> $r/etc/SuSEconfig/profile.SuSEconfig
    echo "setenv RASMOLPATH /usr/lib/rasmol" >> $r/etc/SuSEconfig/csh.cshrc.SuSEconfig
fi
if test -d $r/usr/lib/mars_e ; then
    echo "DMARSCONF=/usr/lib/mars_e" >> $r/etc/SuSEconfig/profile.SuSEconfig
    echo "export DMARSCONF" >> $r/etc/SuSEconfig/profile.SuSEconfig
    echo "setenv DMARSCONF /usr/lib/mars_e" >> $r/etc/SuSEconfig/csh.cshrc.SuSEconfig
fi
if test -d $r/usr/lib/crisp/macros ; then
    echo "CRPATH=/usr/lib/crisp/macros" >> $r/etc/SuSEconfig/profile.SuSEconfig
    echo "export CRPATH" >> $r/etc/SuSEconfig/profile.SuSEconfig
    echo "setenv CRPATH /usr/lib/crisp/macros" >> $r/etc/SuSEconfig/csh.cshrc.SuSEconfig
fi
if test -d $r/usr/lib/cint ; then
    echo "CINTSYSDIR=/usr/lib/cint" >> $r/etc/SuSEconfig/profile.SuSEconfig
    echo "export CINTSYSDIR" >> $r/etc/SuSEconfig/profile.SuSEconfig
    echo "setenv CINTSYSDIR /usr/lib/cint" >> $r/etc/SuSEconfig/csh.cshrc.SuSEconfig
fi
if test -d $r/usr/lib/maxwell ; then
    echo "MAXHOME=/usr/lib/maxwell" >> $r/etc/SuSEconfig/profile.SuSEconfig
    echo "export MAXHOME" >> $r/etc/SuSEconfig/profile.SuSEconfig
    echo "setenv MAXHOME /usr/lib/maxwell" >> $r/etc/SuSEconfig/csh.cshrc.SuSEconfig
fi
if test -d $r/usr/X11R6/lib/blender ; then
    echo "BLENDERDIR=/usr/X11R6/lib/blender" >> $r/etc/SuSEconfig/profile.SuSEconfig
    echo "export BLENDERDIR" >> $r/etc/SuSEconfig/profile.SuSEconfig
    echo "setenv BLENDERDIR /usr/X11R6/lib/blender" >> $r/etc/SuSEconfig/csh.cshrc.SuSEconfig
fi
if test -n "$HTTP_PROXY" ; then
    echo "http_proxy=$HTTP_PROXY" >> $r/etc/SuSEconfig/profile.SuSEconfig
    echo "export http_proxy" >> $r/etc/SuSEconfig/profile.SuSEconfig
    echo "setenv http_proxy $HTTP_PROXY" >> $r/etc/SuSEconfig/csh.cshrc.SuSEconfig
fi
if test -n "$FTP_PROXY" ; then
    echo "ftp_proxy=$FTP_PROXY" >> $r/etc/SuSEconfig/profile.SuSEconfig
    echo "export ftp_proxy" >> $r/etc/SuSEconfig/profile.SuSEconfig
    echo "setenv ftp_proxy $FTP_PROXY" >> $r/etc/SuSEconfig/csh.cshrc.SuSEconfig
fi
if test -n "$GOPHER_PROXY" ; then
    echo "gopher_proxy=$GOPHER_PROXY" >> $r/etc/SuSEconfig/profile.SuSEconfig
    echo "export gopher_proxy" >> $r/etc/SuSEconfig/profile.SuSEconfig
    echo "setenv gopher_proxy $GOPHER_PROXY" >> $r/etc/SuSEconfig/csh.cshrc.SuSEconfig
fi
if test -n "$NO_PROXY" ; then
    echo "no_proxy='$NO_PROXY'" >> $r/etc/SuSEconfig/profile.SuSEconfig
    echo "export no_proxy" >> $r/etc/SuSEconfig/profile.SuSEconfig
    echo "setenv no_proxy '$NO_PROXY'" >> $r/etc/SuSEconfig/csh.cshrc.SuSEconfig
fi

WINDOWMANAGER=`type -p $DEFAULT_WM`
test -z "$WINDOWMANAGER" -a -n "$DEFAULT_WM" && {
    test -x /usr/X11R6/bin/$DEFAULT_WM && \
        WINDOWMANAGER=/usr/X11R6/bin/$DEFAULT_WM
}
test -z "$WINDOWMANAGER" && WINDOWMANAGER=/usr/X11R6/bin/kde
echo "test -z \"\$WINDOWMANAGER\" && WINDOWMANAGER=$WINDOWMANAGER" >> $r/etc/SuSEconfig/profile.SuSEconfig
echo "export WINDOWMANAGER" >> $r/etc/SuSEconfig/profile.SuSEconfig
echo "if ( ! \${?WINDOWMANAGER} ) setenv WINDOWMANAGER $WINDOWMANAGER" >> $r/etc/SuSEconfig/csh.cshrc.SuSEconfig

test -n "$CONSOLE_MAGIC" && {
    	echo "# The following sequence is needed for most non-west-european languages" >> $r/etc/SuSEconfig/profile.SuSEconfig
	echo "test \"\$TERM\" = \"linux\" && echo -en \"\\033"$CONSOLE_MAGIC\"\
 >> $r/etc/SuSEconfig/profile.SuSEconfig
    	echo "# The following sequence is needed for most non-west-european languages" >> $r/etc/SuSEconfig/csh.login.SuSEconfig
    echo "test \"\$TERM\" = \"linux\" && echo -n \"\\033"$CONSOLE_MAGIC\" >> $r/etc/SuSEconfig/csh.login.SuSEconfig
}

check_md5_and_move $r/etc/SuSEconfig/profile
check_md5_and_move $r/etc/SuSEconfig/csh.login
check_md5_and_move $r/etc/SuSEconfig/csh.cshrc

if test "$SORT_PASSWD_BY_UID" = yes ; then
    for i in passwd group ; do
        cat $r/etc/$i | grep "^root:" > $r/etc/$i.t
        cat $r/etc/$i | grep -v "^+" | grep -v ":-[0-9]:-[0-9]:" | \
            grep -v "^root:" | sort -n -t : +2 >> $r/etc/$i.t
        test -s $r/etc/$i.t && {
            cat $r/etc/$i | grep ":-[0-9]:-[0-9]:" >> $r/etc/$i.t
            cat $r/etc/$i | grep "^+" >> $r/etc/$i.t
            cmp -s $r/etc/$i $r/etc/$i.t || {
                echo "Sorting /etc/$i. Saving old to /etc/$i.unsorted."
                mv $r/etc/$i $r/etc/$i.unsorted
                cp $r/etc/$i.t $r/etc/$i 
            }
        }
        rm $r/etc/$i.t
    done
fi

#
# Now set ROOT_LOGIN_REMOTE.
#
if test -n "$ROOT_LOGIN_REMOTE" ; then
    if test "$ROOT_LOGIN_REMOTE" = "yes" ; then
        cat $r/etc/login.defs | \
            sed -e"s:^[ 	]*CONSOLE[ 	]:#CONSOLE	:" \
            > $r/etc/login.defs.SuSEconfig
    else
        cat $r/etc/login.defs | \
            sed -e"s:^#[ 	]*CONSOLE[ 	]:CONSOLE	:" \
            > $r/etc/login.defs.SuSEconfig
    fi
    check_md5_and_move $r/etc/login.defs
fi

#
# check login mode
#
test "$CHECK_INITTAB" = yes && {
    if [ ! -r $r/etc/XF86Config -a "$DISPLAYMANAGER" != console ]; then
        echo -n "XFree86 not configured yet! No graphical login. "
        echo "Check /etc/XF86Config."
        DISPLAYMANAGER=none
    fi

    case "$DISPLAYMANAGER" in
        kdm|KDM|xdm|XDM) INITRL=3;;
        *)               INITRL=2;;
    esac

    case "$CONSOLE_SHUTDOWN" in
        ignore)
          CA_SEARCH="^ca::ctrlaltdel.*"
          CA_LINE="#ca::ctrlaltdel:/sbin/shutdown -h -t 4 now"
        ;;
        halt)
          CA_SEARCH="^ca::ctrlaltdel.*"
          CA_LINE="ca::ctrlaltdel:/sbin/shutdown -h -t 4 now"
        ;;
        reboot)
          CA_SEARCH="^ca::ctrlaltdel.*"
          CA_LINE="ca::ctrlaltdel:/sbin/shutdown -r -t 4 now"
        ;;
        *)
          CA_SEARCH="wrzlgnmpf-this-should-not-be-found"
          CA_LINE=""
        ;;
    esac

    cp -p $r/etc/inittab $r/etc/inittab.SuSEconfig || {
        echo "Unexpected Error - emergency exit..."
        rm -f $IS_RUNNING
        exit 1
    }

    cat $r/etc/inittab | \
        sed -e "s%^id:[0-9sSa-cA-C]*:initdefault:%id:$INITRL:initdefault:%" -e \
               "s%$CA_SEARCH%$CA_LINE%" \
        > $r/etc/inittab.SuSEconfig

    test -s $r/etc/inittab.SuSEconfig || {
        echo "Unexpected Error - emergency exit..."
        rm -f $IS_RUNNING
        exit 1
    }

    cmp -s $r/etc/inittab.SuSEconfig $r/etc/inittab || {
        mv $r/etc/inittab.SuSEconfig $r/etc/inittab
        echo "Installing new $r/etc/inittab"
    }
    rm -f $r/etc/inittab.SuSEconfig
    unset INITRL
}

#
# setting dosemu security level.
#
if test -n "$PERMISSION_SECURITY" ; then
    for LEVEL in $PERMISSION_SECURITY ; do
        if test -f $r/etc/dosemu.users.$LEVEL -a \
                -L $r/etc/dosemu.users ; then
            rm -f $r/etc/dosemu.users
            ln -s dosemu.users.$LEVEL $r/etc/dosemu.users
        fi
    done
fi

test -x /sbin/ldconfig -a -z "$r" -a "$CHECK_NEWPACKAGE" != false && \
    /sbin/ldconfig


#
# the following stuff should be done in running system...
#
# first things, that have to be done in 'normal' systems as well as in
# 'demo mode' system.
#
if test -z "$r" ; then
    if test "$FASTRUN" = "true" ; then
        SUB_SCRIPTS="/sbin/conf.d/SuSEconfig.sendmail /sbin/conf.d/SuSEconfig.ypclient"
    else
        SUB_SCRIPTS="/sbin/conf.d/SuSEconfig.*"
    fi
    #
    # Now start the package skripts
    #
    for SKRIPT in $SUB_SCRIPTS ; do
        test -f $SKRIPT || continue
        case "$SKRIPT" in
          *~|*.swp|*.bak|*.sav|*.save|*.rpmsave|*.rpmorig|*.rpmnew)
            continue
            ;;
          *)
            echo Executing $SKRIPT...
            bash $SKRIPT
            ;;
        esac
    done
fi


#
# Now do things, only allowed in running 'normal' system.
#
if test -z "$r" -a ! -e $r/usr/lib/YaST/.DemoMode ; then
    #
    # we have only one package with a /usr/bin/vi symlink, but several vi
    # packages. If it does not exist, create it
    #
    if test ! -e /usr/bin/vi ; then
        rm -f /usr/bin/vi
        test -e /usr/bin/xvi && ln -s xvi /usr/bin/vi
        test -e /usr/bin/nvi && ln -s nvi /usr/bin/vi
        test -e /usr/bin/elvis && ln -s elvis /usr/bin/vi
        test -e /usr/bin/vim && ln -s vim /usr/bin/vi
    fi

    if test "$FASTRUN" != "true" ; then
        if test -x /sbin/depmod ; then
            MOD_DIR=/lib/modules/`uname -r`
            if test -d $MOD_DIR ; then
                /sbin/depmod -a 2> /dev/null > /dev/null
            fi
        fi

        if test "$HOW_TO_HANDLE_COMMERCIAL_LIBS" = link -o \
                "$HOW_TO_HANDLE_COMMERCIAL_LIBS" = clean ; then
            if test -x /usr/bin/ldd -a \
                    -x /usr/bin/dirname -a \
                    -x /usr/bin/basename ; then
                for DYNBIN in /bin/*.SuSE-dynamic \
                              /sbin/*.SuSE-dynamic \
                              /usr/bin/*.SuSE-dynamic \
                              /usr/sbin/*.SuSE-dynamic \
                              /usr/X11R6/bin/*.SuSE-dynamic ; do
                    test -x $DYNBIN || continue
                    DYNDIR=`/usr/bin/dirname $DYNBIN`
                    DYNBASE=`/usr/bin/basename $DYNBIN .SuSE-dynamic`
                    test -e $DYNDIR/$DYNBASE -a ! -L $DYNDIR/$DYNBASE && {
                        echo skipping $DYNBIN. $DYNDIR/$DYNBASE is not a link...
                        continue
                    }
                    test ! -e $DYNDIR/$DYNBASE.SuSE-static -a \
                           "$HOW_TO_HANDLE_COMMERCIAL_LIBS" != clean && {
                        echo skipping $DYNBIN. $DYNDIR/$DYNBASE.SuSE-static does not exist...
                        continue
                    }
                    LIBS_MISSING=false
                    for DUMMY in `/usr/bin/ldd $DYNBIN | grep "not found"` ; do
                        LIBS_MISSING=true
                    done
                    if test "$LIBS_MISSING" = true ; then
                        USEDDYN=$DYNBASE.SuSE-static
                        OTHERDYN=$DYNDIR/$DYNBASE.SuSE-dynamic
                    else
                        USEDDYN=$DYNBASE.SuSE-dynamic
                        OTHERDYN=$DYNDIR/$DYNBASE.SuSE-static
                    fi
                    test -e $DYNDIR/$USEDDYN || {
                        echo skipping $DYNBIN - please check for $USEDDYN...
                        continue
                    }
                    rm -f $DYNDIR/$DYNBASE
                    ln -s $USEDDYN $DYNDIR/$DYNBASE
                    test "$HOW_TO_HANDLE_COMMERCIAL_LIBS" = clean -a \
                         -e "$OTHERDYN" && {
                        echo deleting obsolete $OTHERDYN...
                        rm -f $OTHERDYN
                    }
                done
            fi
        fi

        for i in 100dpi Type1 75dpi cyrillic misc Speedo local ; do
            FDIR=/usr/X11R6/lib/X11/fonts/$i
            if test -d $FDIR -a -x /usr/X11R6/bin/mkfontdir -a \
                "$CHECK_NEWPACKAGE" != false ; then
                if [ ! -f $FDIR/fonts.dir -o $FDIR -nt $FDIR/fonts.dir ] ; then 
                    echo "Updating X11 font directory $i..." 
                    /usr/X11R6/bin/mkfontdir $FDIR 
                fi
            fi
        done

        if test -n "$CREATE_INFO_DIR" -a "$CREATE_INFO_DIR" = "yes" -a \
            "$CHECK_NEWPACKAGE" != false ; then
            if test -x /usr/bin/perl -a -d /usr/info/ ; then
                if test ! -f /usr/info/dir -o /usr/info/dir -ot /usr/info/ \
                    -o /usr/info/dir -ot /usr/lib/info/ \
                    -o /usr/info/dir -ot /usr/local/info/ \
                    -o /usr/info/dir -ot /usr/local/lib/info/ \
                    -o /usr/info/dir -ot /usr/X11R6/info/ \
                    -o /usr/info/dir -ot /usr/X11R6/lib/info/ \
                    -o /usr/info/dir -ot /usr/X11R6/lib/xemacs/info/ \
                    ; then
                    my_test_write /usr/info && {
                        echo "Creating /usr/info/dir..."
                        /usr/bin/mkinfodir 
                    }
                fi
            fi
        fi

        if test -x /usr/bin/mandb -a "$CHECK_NEWPACKAGE" != false ; then
            echo "Processing index files of all manpages..."
            /usr/bin/mandb -q -s
        fi
    fi

    if test -n "$CHECK_PERMISSIONS" -a -e /etc/permissions -a \
            -x /usr/bin/perl -a -x /usr/bin/chkstat ; then
        if test "$CHECK_PERMISSIONS" = "set" ; then
            /usr/bin/chkstat -set /etc/permissions
            for PERMEXT in $PERMISSION_SECURITY ; do
                test -e /etc/permissions."$PERMEXT" &&\
                    /usr/bin/chkstat -set \
                        /etc/permissions."$PERMEXT"
            done
        elif test "$CHECK_PERMISSIONS" = "warn" ; then
            /usr/bin/chkstat /etc/permissions
            for PERMEXT in $PERMISSION_SECURITY ; do
                test -e /etc/permissions."$PERMEXT" &&\
                    /usr/bin/chkstat \
                        /etc/permissions."$PERMEXT"
            done
        fi
    fi

    if test ! -e /sbin/conf.d/SuSEconfig.sendmail -a ! -e /etc/aliases.db ; then
        #
        # maybe we have smail installed - make sure /etc/aliases is setup
        # correctly
        #
        NEWALIASES=`type -p newaliases`
        test -n "$NEWALIASES" && eval $NEWALIASES
    fi
fi

#
# now look for reports and mail them
#
if test -z "$r" -a "$SENDMAIL_TYPE" != "YAST_ASK" -a \
    -x /usr/bin/mail -a -x /usr/sbin/sendmail -a \
    -n "$MAIL_REPORTS_TO" -a "$FASTRUN" != "true" ; then
    if test "$MAIL_LEVEL" = all ; then
        FILES_TO_MAIL="/var/adm/notify/messages/* \
                       /var/adm/notify/warnings/* \
                       /var/adm/notify/log/*"
    else
        FILES_TO_MAIL="/var/adm/notify/messages/* \
                       /var/adm/notify/warnings/*"
    fi
    for FILE in $FILES_TO_MAIL ; do
        test -f $FILE || continue
        cat $FILE | /usr/bin/mail $MAIL_REPORTS_TO \
            -s "SuSEconfig: `basename $FILE`"
        rm -f $FILE
        sleep 2
    done
    rm -f /var/adm/notify/log/*
fi

#
# Now store date for next call
#
if test -z "$r" -a "$FASTRUN" != "true" ; then
    if test -x /bin/date ; then
        /bin/date > $LASTRUN
    else
        cat /dev/null > $LASTRUN
    fi
fi

#
# we have finished and can remove our lock file.
#
rm -f $IS_RUNNING

echo "Finished."
exit 0
