#!/bin/sh
#
#
# clean_catman. This script was split off cron.daily
# Please add your local changes to cron.daily.local
# since this file will be overwritten, when updating your system.
#
# Copyright (c) 1996-2000 SuSE GmbH Nuernberg, Germany.   
#
# please send bugfixes or comments to feedback@suse.de.
#
# Author: Burchard Steinbild <bs@suse.de>, 1996
#         Florian La Roche <florian@suse.de>, 1996
#


#
# paranoia settings
#
umask 022

PATH=/sbin:/bin:/usr/sbin:/usr/bin
export PATH

#
# get information from /etc/rc.config
#
if [ -f /etc/rc.config ] ; then
    . /etc/rc.config
fi
if [ -f /etc/sysconfig/cron_daily ] ; then
    . /etc/sysconfig/cron_daily
fi

#
# Delete too old preformatted man-pages.
#
if [ "$DELETE_OLD_CATMAN" = yes ] ; then
  if [ -z "$CATMAN_ATIME" ] ; then
    # Default is 7 days
    CATMAN_ATIME=7
  fi
  test -e /var/cache/man && \
      find /var/cache/man -name '*.gz' -type f -atime +$CATMAN_ATIME  -print0 | \
      xargs --no-run-if-empty --max-lines=200 --null -- rm -f
fi

exit 0
