#!/bin/sh
#
#
# cron.daily. This script is executed as a cron-job in the 
# early morning-hours. Please add your local changes to cron.daily.local
# since this file will be overwritten, when updating your system.
#
# Copyright (c) 1996-2002 SuSE Linux AG, Nuernberg, Germany.   
#
# please send bugfixes or comments to feedback@suse.de.
#
# Author: Burchard Steinbild <feedback@suse.de>, 1996
#         Florian La Roche <feedback@suse.de>, 1996
#


#
# paranoia settings
#
umask 022

PATH=/sbin:/bin:/usr/sbin:/usr/bin
export PATH

#
# get information from /etc/rc.config
#
if [ -f /etc/rc.config ] ; then
    . /etc/rc.config
fi

# Delete too old nvi-saved files.
if test -d /var/tmp/vi.recover; then
    find /var/tmp/vi.recover -type f -mtime +7 -exec rm -f -- {} \;
fi

# Recover nvi-saved files.
if test -x /usr/sbin/recover.nvi; then
    /usr/sbin/recover.nvi
fi

#
# check CMOS Battery
#
test -r /proc/driver/rtc && {
    test $(awk '$1 == "batt_status" { print $3 }' /proc/driver/rtc) != "okay" && \
        echo "CMOS battery empty -- expect problems"
}
test -r /proc/rtc && {
    test $(awk '$1 == "batt_status" { print $3 }' /proc/rtc) != "okay" && \
        echo "CMOS battery empty -- expect problems"
}

# now start the local cron.daily file, if it exists.

if [ -f /root/bin/cron.daily.local ] ; then
    . /root/bin/cron.daily.local
fi

exit 0
