#!/bin/sh
#
#
# do_mandb. This script was split off cron.daily.
# Please add your local changes to cron.daily.local
# since this file will be overwritten, when updating your system.
#
# Copyright (c) 1996-2000 SuSE GmbH Nuernberg, Germany.   
#
# please send bugfixes or comments to feedback@suse.de.
#
# Author: Burchard Steinbild <bs@suse.de>, 1996
#         Florian La Roche <florian@suse.de>, 1996
#

#
# paranoia settings
#
umask 022

PATH=/sbin:/bin:/usr/sbin:/usr/bin
export PATH

#
# get information from /etc/rc.config
#
if [ -f /etc/rc.config ] ; then
    . /etc/rc.config
fi

#
# now we do the man page stuff
#
if test "$REINIT_MANDB" = yes ; then
    if test -x /usr/bin/mandb ; then
        rm -f /var/catman/index.bt
        /usr/bin/mandb -q -s 2> /dev/null || {
            echo There seem to be trouble with mandb.
            echo
            echo please run /usr/bin/mandb an check the output...
        }
    fi
    #
    # some applications need whatis database. If makewhatis exists, call it
    #
    if [ -x /usr/sbin/makewhatis -a -w /usr/man ] ; then
        unset MANPATH manpath
        manpath=/usr/share/man:/usr/man:/usr/X11R6/man:/usr/local/man
        for DIR in /usr/openwin/man /usr/man/allman /usr/man/de ; do
            test -d $DIR && manpath=$manpath:$DIR
        done
        MANPATH=$manpath
        export manpath MANPATH

        /usr/sbin/makewhatis
    fi
fi

exit 0
