#! /bin/sh
#
# Copyright (c) 1996 SuSE GmbH Nuernberg, Germany.  All rights reserved.
#
# Author: Florian La Roche <florian@suse.de>, 1996
#	  Werner Fink <werner@suse.de>, 1996,2000
#
# /etc/init.d/cron
#
## BEGIN INIT INFO
# Provides:          cron
# Required-Start:    $remote_fs $syslog xntpd sendmail
# Required-Stop:
# Default-Start:     2 3 5
# Default-Stop:
# Description:       Cron job service
## END INIT INFO

. /etc/rc.status
. /etc/rc.config

base=${0##*/}
link=${base#*[SK][0-9][0-9]}

test $link = $base && CRON=yes
test "$CRON" = yes || exit 0

test -x /usr/sbin/cron || exit 0

rc_reset
case "$1" in
    start)
        echo -n "Starting CRON daemon"
	startproc /usr/sbin/cron
	rc_status -v
	;;
    stop)
	echo -n "Shutting down CRON daemon"
	killproc -TERM /usr/sbin/cron
	rc_status -v
	;;
    restart)
	$0 stop && $0 start
	rc_status
	;;
    reload)
	# CRON will examine when a crontab file was modified
	;;
    status)
	echo -n "Checking for CRON daemon"
	checkproc /usr/sbin/cron && echo "CRON is up" || echo "No CRON daemon"
	;;
    probe)
	# CRON will examine when a crontab file was modified
	;;
    *)
	echo "Usage: $0 {start|stop|status|restart}"
	exit 1
esac
rc_exit
