#! /bin/bash
# Copyright (c) 1996-99 SuSE GmbH Nuernberg, Germany.  All rights reserved.
#
# Author: Florian La Roche <florian@suse.de>, 1996
#	  Werner Fink <werner@suse.de>, 1996,98,99
#         Martin Scherbaum <maddin@suse.de>, 1997
#         Reinhard Max <max@suse.de>, 1997
#
# /etc/init.d/xdm
#
### BEGIN INIT INFO
# Provides:          xdm
# Required-Start:    $remote_fs $syslog ypclient
# Required-Stop:
# Default-Start:     5
# Default-Stop:
# Description:       X Display Manager
### END INIT INFO

. /etc/rc.status
. /etc/rc.config
. /etc/SuSEconfig/profile

locale_vars="\
LANG         \
LC_ALL       \
LC_MESSAGES  \
LC_CTYPE     \
LC_COLLATE   \
LC_TIME      \
LC_NUMERIC   \
LC_MONETARY"

for var in $locale_vars
do
    if eval test -z "\$$var"; then
        eval $var="\$RC_$var"
        export $var
    fi
done

case "$DISPLAYMANAGER" in
    kdm|kde|KDM|KDE)	 DISPLAYMANAGER=/opt/kde/bin/kdm
			 test -x /opt/kde2/bin/kdm && \
			 DISPLAYMANAGER=/opt/kde2/bin/kdm  ;;
    gdm|GDM|Gnome|GNOME) DISPLAYMANAGER=/opt/gnome/bin/gdm ;;
    wdm|WDM)		 DISPLAYMANAGER=/usr/X11R6/bin/wdm ;;
    *)			 DISPLAYMANAGER=/usr/X11R6/bin/xdm ;;
esac
test ! -x "$DISPLAYMANAGER" && DISPLAYMANAGER=/usr/X11R6/bin/xdm

DM=${DISPLAYMANAGER##*/}

rc_reset
case "$1" in
    start)
	echo -n "Starting service $DM"
	startproc $DISPLAYMANAGER || rc_failed
	# After a crash or a kill signal we may have
	# a wrong owner ship of /dev/xconsole
	if rc_status ; then
	    if test -x /etc/X11/xdm/TakeDevices ; then
		/etc/X11/xdm/TakeDevices
	    else
		chown root:tty /dev/xconsole /dev/tty0
		chmod 622      /dev/xconsole /dev/tty0
	    fi
	fi
	rc_status -v
	;;
    stop)
	echo -n "Shutting down service $DM"
	# 
	# killproc(8) sleep upto five seconds and sends
	# SIGKILL if xdm does not terminate within
	#
	killproc -TERM $DISPLAYMANAGER
	rc_status -v
	;;
    restart)
	$0 stop && $0 start
	rc_status
	;;
    reload)
	echo -n "Reload service $DM"
	killproc -HUP  $DISPLAYMANAGER || return=$rc_failed
	echo -e "$return"
	;;
    status|check)
	echo -n "Checking for service ${DM}: "
	checkproc $DISPLAYMANAGER && echo "is running" || echo "is NOT running"
	;;
    probe)
	XDMDIR=/usr/X11R6/lib/X11/xdm
	if test $XDMDIR/xdm-config -nt /var/run/xdm.pid -o \
	        $XDMDIR/Xservers   -nt /var/run/xdm.pid
	then
	    echo reload
	fi
	;;
    *)
	echo "Usage: $0 {start|stop|status|restart|reload|probe}"
	exit 1
esac
rc_exit
