#!/bin/sh

# (C) 1997-2002 SuSE Linux AG, Nuernberg, Germany
# Klaus Franken <feedback@suse.de> 25.02.1998
# Remo Behn <feedback@suse.de> 18.07.1998
# Send suggestions and comments to feedback@suse.de

BASENAME=${0##*/}
INTERFACE=$1
DEVICE=$2
SPEED=$3
LOCALIP=$4
REMOTEIP=$5

if [ -z "$REMOTEIP" ]; then
    echo "Usage: $0 <INTERFACE> <DEVICE> <SPEED> <LOCALIP> <REMOTEIP>"
    exit 1
fi

TERM=raw
export TERM

test -e /etc/sysconfig/network/options && . /etc/sysconfig/network/options

check_srv() {
	RLVL=`/sbin/runlevel | sed 's/. //'`
	test -L /etc/init.d/rc${RLVL}.d/S??$1 && return 0
	return 1
}	

start_firewall() {
	case `uname -r` in
	    2.[345].*)
		if check_srv SuSEfirewall2_setup; then
		    /sbin/SuSEfirewall2 start
		else
		  if check_srv SuSEfirewall_setup; then
		    /sbin/SuSEfirewall start
		  fi
		fi
		;;
	    *)  
		if check_srv SuSEfirewall_setup; then
		    /sbin/SuSEfirewall start
		fi
		;;
	esac
	# KG: Probably not correct any more: Should check symlinks as well
	test -x /sbin/SuSEpersonal-firewall && . /sbin/SuSEpersonal-firewall
}

case "$INTERFACE" in
ippp*)

    # find the device
    found=0
    for I in $NETCONFIG $NETCONFIG_PCMCIA; do
	eval NETDEV=\$NETDEV$I
	if [ $NETDEV = $INTERFACE ]; then
	    found=1
	    break;
	fi
    done
    if [ $found -eq 0 ]; then
	echo "Device '$INTERFACE' not configured in '/etc/rc.config'"
	exit 1
    fi

    eval IFCONFIG=\$IFCONFIG$I

    case "$BASENAME" in
    ip-up)
	# Get the nameservers (works with ipppd option ms-get-dns):

	if [ -n "$MS_DNS1" -a "$START_NAMED" != "yes" ]; then
                /sbin/modify_resolvconf modify -s ipppd -e "$INTERFACE" \
                  -p ipppd -f /etc/ppp/ip-up -n "$MS_DNS1 $MS_DNS2" -t - << EOT
                  This is a temporary resolv.conf created by ipppd. The previous
                  file has been saved as <see "Backup: field above>. It will be
                  restored when ippp disconnects.

                  If you don't like ipppd to change your nameserver settings
                  then set MODIFY_RESOLV_CONF_DYNAMICALLY=no in /etc/rc.config
                  or remove the option ms-get-dns from /etc/ppp/options.ippp*.
EOT
	fi

	#
	# SuSE Firewall script: If you installed the package firewals
	# and configured your firewall in /etc/sysconfig/firewall
	# then set START_FW in /etc/rc.config to yes and it will be
	# started here:
	#
	start_firewall

	#
	# You may choose to use a default firewall script, configured for
	# the standard dialup user(install package ipchains):
	#
	#test -x /etc/ppp/inet_chains.local && /etc/ppp/inet_chains.local "$@"

	# maybe you want to start mail services:
	# set follow variables in /etc/sysconfig/sendmail
	#    SENDMAIL_TYPE="yes"
	#    SENDMAIL_SMARTHOST="<ISP-mailserver>"
	#    SENDMAIL_ARGS="-bd -om"
	#    SENDMAIL_EXPENSIVE="yes"
	#    SENDMAIL_NOCANONIFY="yes"
	#/usr/bin/fetchmail -a -v >>/var/log/fetchmail 2>&1 &
	#/usr/sbin/sendmail -q &

	# As an alternative to the commands above, you can use a seperate script,
	# /etc/ppp/poll.tcpip. The default scripts as shipped is able to set the
	# system clock using ntpdate (see the XNTPD_INITIAL_NTPDATE setting in
	# /etc/rc.config). It supports fetchmail with a system-wide
	# /etc/fetchmailrc and can use UUCP to fetch mail over TCP/IP, provided
	# that UUCP is configured properly. Last not least it also calls sendmail
	# to send any queued mail. Uncomment the line below.
	# /etc/ppp/poll.tcpip

	# call ip-up.local if it exists and is executable:
	test -x /etc/ppp/ip-up.local && /etc/ppp/ip-up.local "$@"
	;;
    ip-down)

	# Restore the nameservers (got with ipppd option ms-get-dns):

	if [ -n "$MS_DNS1" -a "$START_NAMED" != "yes" ]; then
                /sbin/modify_resolvconf restore -s ipppd -e "$INTERFACE"
	fi

	# restart interface
	/sbin/ifconfig $INTERFACE $IFCONFIG
	# set routes from /etc/route.conf 
	/etc/init.d/route start $INTERFACE
	#
	# SuSE Firewall script: If you installed the package firewals
	# and configured your firewall in /etc/sysconfig/firewall
	# then set START_FW in /etc/rc.config to yes and it will be
	# started here:
	#
	start_firewall

	# call ip-down.local if it exists and is executable:
	test -x /etc/ppp/ip-down.local && /etc/ppp/ip-down.local "$@"
	;;
    *)
	;;
    esac
    ;;

ppp*)
    # Analog-PPP, add commands as you need...
    case "$BASENAME" in
    ip-up)
	#
	# This code allows automatic configuration of your resolv.conf
	# for peer supplied DNS addresses when using the `usepeerdns'
	# option. Original resolv.conf is restored when ip-down is called
	# by pppd when the link goes down.
	#
	if [ -n "$USEPEERDNS" -a -f /etc/ppp/resolv.conf -a "$START_NAMED" != "yes" ]; then
		/sbin/modify_resolvconf modify -s pppd -p pppd -e "$INTERFACE" \
                  -f /etc/ppp/ip-up -n "$DNS1 $DNS2" -t - << EOT
                  This is a temporary resolv.conf created by pppd. The previous
                  file has been saved as <see Backup: field above>. It will be
                  restored when pppd disconnects.

                  If you do not like pppd to change your nameserver settings
                  then set MODIFY_RESOLV_CONF_DYNAMICALLY=no in /etc/rc.config.
EOT
	fi

	#
	# SuSE Firewall script: If you installed the package firewals
	# and configured your firewall in /etc/sysconfig/firewall
	# then set START_FW in /etc/rc.config to yes and it will be
	# started here:
	#
	start_firewall
	
	#
	# You may choose to use a default firewall script, configured for
	# the standard dialup user(install package ipchains):
	#
	#test -x /etc/ppp/inet_chains.local && /etc/ppp/inet_chains.local "$@"

	# call ip-up.local if it exists and is executable:
	test -x /etc/ppp/ip-up.local && /etc/ppp/ip-up.local "$@"
	;;
    ip-down)
	#
	# This code restores the original resolv.conf saved when ip-up
	# was called by the pppd which uses the `usepeerdns' option and
	# resolv.conf was modified for the supplied dns server adresses.
	#
	if [ -n "$USEPEERDNS" -a -f /etc/ppp/resolv.conf -a "$START_NAMED" != "yes" ]; then
                /sbin/modify_resolvconf restore -s pppd -e "$INTERFACE"
	fi

	#
	# SuSE Firewall script: If you installed the package firewals
	# and configured your firewall in /etc/sysconfig/firewall
	# then set START_FW in /etc/rc.config to yes and it will be
	# started here:
	#
	start_firewall

	# call ip-down.local if it exists and is executable:
	test -x /etc/ppp/ip-down.local && /etc/ppp/ip-down.local "$@"
	;;
    *)
	;;
    esac
    ;;
*)
    # dont know...
    ;;
esac | logger -p security.notice -t $BASENAME
