#! /bin/sh
#
# Copyright (c) 1996 S.u.S.E. GmbH Fuerth, Germany.  All rights reserved.
#
# Author: Florian La Roche <florian@suse.de>, 1996
#	  Werner Fink <werner@suse.de>, 1996
#
# /sbin/init.d/cron
#

. /etc/rc.config

test "$CRON" = yes || exit 0

case "$1" in
    start)
        if test -x /usr/sbin/cron ; then
	    echo "Starting CRON clock daemon."
	    /usr/sbin/cron
        fi
	;;
    stop)
	echo -n "Shutting down CRON clock daemon:"
	killproc -TERM /usr/sbin/cron
	echo
	;;
    *)
	echo "Usage: $0 {start|stop}"
	exit 1
esac

exit 0
