#! /bin/sh
#
# Copyright (c) 1996 S.u.S.E. GmbH Fuerth, Germany.  All rights reserved.
#
# Author: Florian La Roche <florian@suse.de>, 1996
#	  Werner Fink <werner@suse.de>, 1996
#
# /sbin/init.d/cron
#

. /etc/rc.config

base=${0##*/}
link=${base#*[SK][0-9][0-9]}

test $link = $base && CRON=yes
test "$CRON" = yes || exit 0

test -x /usr/sbin/cron || exit 0

return=$rc_done
case "$1" in
    start)
        echo -n "Starting CRON daemon"
	startproc /usr/sbin/cron || return=$rc_failed
	echo -e "$return"
	;;
    stop)
	echo -n "Shutting down CRON daemon"
	killproc -TERM /usr/sbin/cron || return=$rc_failed
	echo -e "$return"
	;;
    retart)
	$0 stop && $0 start || return=$rc_failed
	;;
    reload)
	# CRON will examine when a crontab file was modified
	;;
    status)
	echo -n "Checking for CRON daemon"
	checkproc /usr/sbin/cron && echo "CRON is up" || echo "No CRON daemon"
	;;
    probe)
	# CRON will examine when a crontab file was modified
	;;
    *)
	echo "Usage: $0 {start|stop|status|restart}"
	exit 1
esac

test "$return" = "$rc_done" || exit 1
exit 0
