#! /bin/sh
# Copyright (c) 1996 S.u.S.E. GmbH Fuerth, Germany.  All rights reserved.
#
# Author: Burchard Steinbild <bs@suse.de>, 1996
#
# /sbin/init.d/dummy
#

. /etc/rc.config

case "$1" in
    start)
    if test "$NETCONFIG" != "YAST_ASK" ; then
        if test -n "$SETUPDUMMYDEV" -a "$SETUPDUMMYDEV" = "yes" ; then
            test -n "$IPADDR_0" && ifconfig dummy0 $IPADDR_0 && \
                route add $IPADDR_0 dev dummy0
        fi
    fi
    ;;
    stop)
    if test "$NETCONFIG" != "YAST_ASK" ; then
        if test -n "$SETUPDUMMYDEV" -a "$SETUPDUMMYDEV" = "yes" ; then
            test -n "$IPADDR_0" && ifconfig dummy0 down
        fi
    fi
    ;;
    *)
    echo "Usage: $0 {start|stop}"
    exit 1
esac

exit 0
