#! /bin/sh
# Copyright (c) 1996 SuSE GmbH Nuernberg, Germany.  All rights reserved.
#
# Author: Florian La Roche <florian@suse.de>, 1996
#	  Werner Fink <werner@suse.de>, 1996
#
# /sbin/init.d/halt (and symlinked to reboot)
#

. /etc/rc.config

case "$0" in
	*halt)
		message="The system is halted."
		command="halt"
		;;
	*reboot)
		message="Please stand by while rebooting the system..."
		command="reboot"
		;;
	*)
		echo "$0: call me as \"halt\" or \"reboot\" please!"
		exit 1
		;;
esac

#
# first do local stuff
#
test -e /sbin/init.d/halt.local && {
    echo Running /sbin/init.d/halt.local
    ECHO_RETURN=$rc_done_up
    sh /sbin/init.d/halt.local || ECHO_RETURN=$rc_failed_up
    echo -e "$ECHO_RETURN"
}

# Write to wtmp file before unmounting /var
$command -w 

echo "Sending all processes the TERM signal..."
killall5 -15
echo -e "$rc_done_up"

if [ "$1" = "fast" ]; then
	sleep 1
else
	sleep 5
fi

echo "Sending all processes the KILL signal..."
killall5 -9
echo -e "$rc_done_up"

ECHO_RETURN=$rc_done_up
echo "Turning off swap"
sync ; sync
swapoff -a || ECHO_RETURN=$rc_failed_up
echo -e "$ECHO_RETURN"

UMOUNT_FAILED=false
ECHO_RETURN=$rc_done_up
echo "Unmounting file systems"
umount -avt noproc || {
    UMOUNT_FAILED=true
    ECHO_RETURN=$rc_failed_up
}
echo -e "$ECHO_RETURN"


if [ "$UMOUNT_FAILED" = true ]; then
    echo "Oops: umount failed :-(  --  trying to remount readonly..."
    mounts=/etc/fstab
    test -r /proc/mounts && mounts=/proc/mounts
    while read des fs rest; do
        mount -v -n -o remount,ro $fs
    done < $mounts

    echo "extra sync..."
    sync; sync
    echo "... hope now it's ok to reboot."
fi

umount -anvt proc


# maybe we use Multiple devices
if test -f /etc/mdtab -a -x /sbin/mdadd ; then
    ECHO_RETURN=$rc_done
    echo -n "Disable Multiple Devices"
    /sbin/mdstop -a || ECHO_RETURN=$rc_failed
    echo -e "$ECHO_RETURN"
fi

# on umsdos fs this would lead to an error message. so direct errors to
# /dev/null
mount -no remount,ro / 2> /dev/null
sync

echo $message
exec $command -d -f
