#! /bin/sh
# Copyright (c) 1996 S.u.S.E. GmbH Fuerth, Germany.  All rights reserved.
#
# Author: Florian La Roche <florian@suse.de>, 1996
#	  Werner Fink <werner@suse.de>, 1996
#
# /sbin/init.d/inetd
#

. /etc/rc.config

export PATH=/bin:/usr/bin:/sbin:/usr/sbin
export HOME=/

# This seems to be ugly but our http-rman needs this environment.

export MANPATH=/usr/man:/usr/X11R6/man:/usr/local/man
if [ -d /usr/openwin ] ; then
    export OPENWINHOME=/usr/openwin
    export MANPATH=$MANPATH:/usr/openwin/man
fi
if [ -d /usr/man/de ] ; then
    export MANPATH=/usr/man/de:$MANPATH
fi

test "$START_INETD" = yes || exit 0

case "$1" in
    start)
	echo "Starting INET services. (inetd)"
	/usr/sbin/inetd
	;;
    stop)
	echo -n "Shutting down INET services:"
	killproc -TERM /usr/sbin/inetd
	echo
	;;
    *)
	echo "Usage: $0 {start|stop}"
	exit 1
esac

exit 0
