#! /bin/sh
# Copyright (c) 1996 S.u.S.E. Gmbh Fuerth, Germany.  All rights reserved.
#
# Author: Burchard Steinbild  <bs@suse.de>, 1996
#	  Carsten Hoeger <choeger@suse.de>, 1998
#
# /sbin/init.d/ipfwadm
#

. /etc/rc.config

test -n "$NETCONFIG" -a "$NETCONFIG" != "YAST_ASK" || exit 0

if   test -x /sbin/ipfwadm  -a -e /proc/net/ip_acct     ; then
    ipwatch ()
    {
	/sbin/ipfwadm -A -a -P all -S $1 -D 0/0 || return=$rc_failed
	/sbin/ipfwadm -A -a -P all -S 0/0 -D $1 || return=$rc_failed
    }
    ipunwatch ()
    {
	/sbin/ipfwadm -A -d -P all -S $1 -D 0/0 || return=$rc_failed
	/sbin/ipfwadm -A -d -P all -S 0/0 -D $1 || return=$rc_failed
    }
elif test -x /sbin/ipchains -a -e /proc/net/ip_fwchains ; then
    ipwatch ()
    {
	/sbin/ipchains -A output -s $1 || return=$rc_failed
	/sbin/ipchains -A input -d $1  || return=$rc_failed
    }
    ipunwatch ()
    {
	/sbin/ipchains -D output -s $1 || return=$rc_failed
	/sbin/ipchains -D input -d $1  || return=$rc_failed
    }
else
    exit 0
fi

return=$rc_done
case "$1" in
    start)
	echo -n "Starting IP accounting"
        for I in $NETCONFIG; do
            eval IPADDR=\$IPADDR$I
            test -n "$IPADDR" && ipwatch $IPADDR
        done
	echo -e "$return"
	;;
    stop)
        echo -n "Stopping IP accounting"
        for I in $NETCONFIG; do
            eval IPADDR=\$IPADDR$I
            test -n "$IPADDR" && ipunwatch $IPADDR
        done
	echo -e "$return"
	;;
    status)
	# ????
	;;
    restart|reload)
	$0 stop && $0 start || return=$rc_failed
	;;
    *)
	echo "Usage: $0 {start|stop}"
	exit 1
esac

exit 0
