#! /bin/sh
#
# Copyright (c) 1996 SuSE GmbH Nuernberg, Germany.  All rights reserved.
#
# Author: Burchard Steinbild <bs@suse.de>, 1996
#	  
#
# /sbin/init.d/kerneld
#

. /etc/rc.status
. /etc/rc.config

base=${0##*/}
link=${base#*[SK][0-9][0-9]}

test $link = $base && START_KERNELD=yes
test "$START_KERNELD" = yes || exit 0

test -x /sbin/kerneld             || exit 0
test -e /proc/sys/kernel/modprobe && exit 0

MODLIB="/lib/modules/`uname -r`"

if test ! -d $MODLIB ; then
    echo "No modules found in $MODLIB. No kerneld."
    exit 0
fi

rc_reset
case "$1" in
    start)
	checkproc /sbin/kerneld && {
            killproc /sbin/kerneld 2> /dev/null
	    echo -n "Re-"
        }
	/sbin/kerneld
	rc_status -v1
	;;
    stop)
	echo "Stopping kerneld"
	killproc -TERM /sbin/kerneld
	rc_status -v1
	;;
    restart|reload)
	$0 stop && $0 start
	rc_status
	;;
    status)
	checkproc /sbin/kerneld && echo "OK" || echo "No process"
	;;
    *)
	echo "Usage: $0 {start|stop|status|restart|reload}"
	exit 1
    ;;
esac
rc_exit
