#! /bin/sh
#
# Copyright (c) 1996 S.u.S.E. GmbH Fuerth, Germany.  All rights reserved.
#
# Author: Burchard Steinbild <bs@suse.de>, 1996
#	  
#
# /sin/init.d/kerneld
#

. /etc/rc.config

case "$1" in
    start)
    if test -n "$START_KERNELD" -a "$START_KERNELD" = yes -a \
        -x /sbin/kerneld -a ! -e /proc/sys/kernel/modprobe ; then
        if test -d /lib/modules/`uname -r` ; then
            killproc -TERM /sbin/kerneld > /dev/null
            echo -n "Re-"
            /sbin/kerneld 
        else
            echo "No modules found in /lib/modules/`uname -r`. No kerneld."
        fi
    fi
    ;;
    stop)
    if test -n "$START_KERNELD" -a "$START_KERNELD" = yes -a \
        -x /sbin/kerneld -a ! -e /proc/sys/kernel/modprobe ; then
        if test -d /lib/modules/`uname -r` ; then
            echo -n "Shutting down kerneld:"
            killproc -TERM /sbin/kerneld 
            echo
        else
            echo "No modules found in /lib/modules/`uname -r`. No kerneld."
        fi
    fi
    ;;
    *)
	echo "Usage: $0 {start|stop}"
	exit 1
    ;;
esac

exit 0
