#!/bin/sh
#
# makerunlvl:	Script for runlevel generation
#		Version 0.1
#
# Copyright (c) 1996 S.u.S.E. GmbH Fuerth, Germany.  All rights reserved.
#
# Author: Werner Fink <werner@suse.de>, 1996
#

init_d="/sbin/init.d"
ovwrt=0

usage ()
{
  echo  "$0" 1>&2
  echo  "usage: makerunlvl -r <#runlevel> [-o] script [script [script [...]]]" 1>&2
  echo  "   runlevel 0: reserved for system halt" 1>&2
  echo  "   runlevel 1: reserved for single user mode" 1>&2
  echo  "   runlevel 6: reserved for system reboot" 1>&2
  echo  "   optional option -o: overwrite existing runlevel configuration" 1>&2
  exit 1
}

#
# Option handler
#
while test "$1" != ""; do
  case "$1" in
    -r)
       rlvl="$2"; shift; shift;
       rlvld="rc${rlvl}.d"
       ;;
    -o)
       ovwrt=1; shift;
       ;;
    -*)
       usage
       ;;
     *)
       break
       ;;
  esac;
done

#
# We need clearly defined arguments
#
test "$*" = "" && usage
test $rlvl -ge 2 -a $rlvl -le 5 || usage
modules=$*

m=0
for i in $modules ; do
  m=`expr $m + 1`
done

if   test $m -le 9; then
  d=10
elif test $m -le 18; then
  d=5
elif test $m -le 45; then
  d=2
else
  echo  "$0" 1>&2
  echo  "$0: $m modules are more then 45 modules" 1>&2
  exit 1
fi

#
# The place of the modules
#
test -d $init_d || {
  echo  "$0" 1>&2
  echo  "$0: no directory $init_d" 1>&2
  exit 1
}

cd $init_d

#
# The runlevel sub directory
#
test -d $rlvld || { mkdir $rlvld; chmod 750 $rlvld; }
test -d $rlvld || {
  echo  "$0" 1>&2
  echo  "$0: can not create directory $rlvld" 1>&2
  exit 1
}

cd $rlvld

#
# Check if there is an existing runlevel
#
contens=`ls .`
test "$contens" = "" && ovwrt=1

test $ovwrt -eq 0 && {
  echo  "$0" 1>&2
  echo  "$0: no overwriting of runlevel $rlvl" 1>&2
  exit 1
}

#
# Check the new runlevel
#
for i in $modules ; do
  test -f ../$i || { echo "$0: $init_d/$i does not exist" 1>&2; exit 1; } 
  test -x ../$i || { echo "$0: $init_d/$i is not executable" 1>&2; exit 1; } 
done

#
# Remove existing runlevel
#
rm -f $contens

#
# Create the new runlevel
#
echo    "$0: Creating under $init_d/$rlvld:"
echo -n "  Start modules:"

n=10
for i in $modules ; do
  echo -n " S${n}${i}"
  ln -sf ../$i  S${n}${i}
  n=`expr $n + $d`
done

echo

echo -n "  Stop  modules:"

for i in $modules ; do
  n=`expr $n - $d`
  echo -n " K${n}${i}"
  ln -sf ../$i  K${n}${i}
done

echo

#
# That's it
#
exit 0
