#! /bin/sh
# Copyright (c) 1996 SuSE GmbH Nuernberg, Germany.  All rights reserved.
#
# Author: Florian La Roche <florian@suse.de>, 1996
#	Werner Fink <werner@suse.de>, 1996
#	Burchard Steinbild <bs@suse.de>, 1996
#	Rolf Haberrecker <rolf@suse.de>, 1998
#	Werner Fink <werner@suse.de> (based on a patch of Andries Brouwer) 1999
#
# /sbin/init.d/network
#

. /etc/rc.config

# Determine the base and follow a runlevel link name.
base=${0##*/}
link=${base#*[SK][0-9][0-9]}

# Be compatible with older SuSE Linux versions
if test "$DHCLIENT" = "yes" -a "$NETCONFIG" = "_0" ; then
    test -z "${IFCONFIG_0}" && \
    test "${IFCONFIG_1}" != "dhcpclient" &&
    test "${IFCONFIG_2}" != "dhcpclient" &&
    test "${IFCONFIG_3}" != "dhcpclient" && IFCONFIG_0="dhcpclient"
fi

# If not called by a runlevel directory, maybe the device
# is given as *second* argument
if test $link = $base -a -n "$2" ; then
    NETCONFIG=""
    for I in _0 _1 _2 _3; do
	eval NETDEV=\$NETDEV$I
	test "$2" = "$NETDEV" && NETCONFIG="$I"
    done
fi

test -n "$NETCONFIG" -a "$NETCONFIG" != "YAST_ASK" || exit 0

return=$rc_done
case "$1" in
    start)
	for I in $NETCONFIG; do
	    eval NETDEV=\$NETDEV$I
	    eval IFCONFIG=\$IFCONFIG$I
	    case "$IFCONFIG" in
		bootp)
		    /sbin/bootp $NETDEV -v
		    continue
		    ;;
		dhcpclient)
		    # Will be done in dhclient boot script, therefore
		    continue
		    ;;
	    esac
	    case $NETDEV in
		ippp*|ppp*|isdn*)
		    # Will be done in i4l boot scripts, therefore
		    continue
		    ;;
		*)
		    return=$rc_done_up
		    echo "Setting up network device $NETDEV"
		    ifconfig $NETDEV $IFCONFIG || return=$rc_failed_up
		    echo -e "$return"
		    ;;
	    esac
	done
	;;
    stop)
	if test -x /usr/bin/wall -a -z "$2" ; then
	    echo "Network is going down now!" | /usr/bin/wall
	    sleep 1
	fi
	REVNETCONFIG=""
	for I in $NETCONFIG; do
	    REVNETCONFIG="$I $REVNETCONFIG"
	done
	for I in $REVNETCONFIG; do
	    eval NETDEV=\$NETDEV$I
	    eval IFCONFIG=\$IFCONFIG$I
	    case "$IFCONFIG" in
		bootp)
		    # We handle devices set up by bootp
		    ;;
		dhcpclient)
		    # Will be done in dhclient boot script, therefore
		    continue
		    ;;
	    esac
	    case $NETDEV in
		ippp*|ppp*|isdn*)
		    # Will be done in i4l boot scripts, therefore
		    continue
		    ;;
		*:*) 
		    # *:* is probably an alias and will fail to ifconfig down
		    # so omit error message
		    ifconfig $NETDEV down 2> /dev/null
		    ;;
		*)
		    echo -n "Shutting down network device $NETDEV"
		    ifconfig $NETDEV down || return=$rc_failed
		    echo -e "$return"
	    esac
	done
	;;
    restart|reload)
	$0 stop ${2+"$2"} && $0 start ${2+"$2"} || return=$rc_failed
	;;
    status)
	for I in $NETCONFIG; do
	    eval NETDEV=\$NETDEV$I
	    case $NETDEV in
		ippp*|ppp*|isdn*)
		    # Should be done in i4l boot scripts, therefore
		    continue
		    ;;
		*)
		    ifconfig $NETDEV
	    esac
	done
	;;
    probe)
	r=""
	for I in $NETCONFIG; do
	    eval NETDEV=\$NETDEV$I
	    case $NETDEV in
		ippp*|ppp*|isdn*)	;;
		*)
		    case "`ifconfig $NETDEV 2>&1`" in
			${NETDEV}*UP*) ;;
			${NETDEV}*)	r=restart
		    esac
	    esac
	done
	test -n "$r" && echo $r
	;;
    *)
    echo "Usage: $0 {start|stop|status|reload|restart|probe}"
    exit 1
esac

test "$return" = "$rc_done" -o "$return" = "$rc_done_up" || exit 1
exit 0
