#! /bin/sh
# Copyright (c) 1996 S.u.S.E. GmbH Fuerth, Germany.  All rights reserved.
#
# Author: Florian La Roche <florian@suse.de>, 1996
#      Werner Fink <werner@suse.de>, 1996
#      Burchard Steinbild <bs@suse.de>, 1996
#
# /sbin/init.d/network
#

. /etc/rc.config

case "$1" in
    start)
    if test -n "$NETCONFIG" -a "$NETCONFIG" != "YAST_ASK" ; then
        for I in $NETCONFIG; do
            eval NETDEV=\$NETDEV$I
            eval IFCONFIG=\$IFCONFIG$I
            case $NETDEV in
              ippp*)
                ;;
              ppp*)
                ;;
              isdn*)
                ;;
              *)
                echo "Setting up network device $NETDEV."
                ifconfig $NETDEV $IFCONFIG
                ;;
            esac
        done
    fi
    ;;
    stop)
    if test -n "$NETCONFIG" -a "$NETCONFIG" != "YAST_ASK" ; then
        if test -x /usr/bin/wall ; then
            echo "Network is going down now." | /usr/bin/wall
            sleep 1
        fi
        for I in $NETCONFIG; do
            eval NETDEV=\$NETDEV$I
            case $NETDEV in
              ippp*)
                ;;
              ppp*)
                ;;
              isdn*)
                ;;
              *)
                echo "Shutting down network device $NETDEV."
                ifconfig $NETDEV down
                ;;
            esac
        done
    fi
    ;;
    *)
    echo "Usage: $0 {start|stop}"
    exit 1
esac

exit 0
