#! /bin/sh
# Copyright (c) 1996 S.u.S.E. GmbH Fuerth, Germany.  All rights reserved.
#
# Author: Florian La Roche <florian@suse.de>, 1996
#      Werner Fink <werner@suse.de>, 1996
#      Burchard Steinbild <bs@suse.de>, 1996
#      Rolf Haberrecker <rolf@suse.de>, 1998
#
# /sbin/init.d/network
#

. /etc/rc.config

test -n "$DHCLIENT"  -a "$DHCLIENT" = "yes" && exit 0
test -n "$NETCONFIG" -a "$NETCONFIG" != "YAST_ASK" || exit 0

return=$rc_done
case "$1" in
    start)
        for I in $NETCONFIG; do
            eval NETDEV=\$NETDEV$I
            eval IFCONFIG=\$IFCONFIG$I
            case $NETDEV in
              ippp*|ppp*|isdn*) ;;
              *)
		if test "$IFCONFIG" = bootp
		then
		    /sbin/bootp $NETDEV -v
		else
                    return=$rc_done_up
		    echo "Setting up network device $NETDEV"
                    ifconfig $NETDEV $IFCONFIG || return=$rc_failed_up
		    echo -e "$return"
		fi
                ;;
            esac
        done
	;;
    stop)
        if test -x /usr/bin/wall ; then
            echo "Network is going down now!" | /usr/bin/wall
            sleep 1
        fi
        for I in $NETCONFIG; do
            eval NETDEV=\$NETDEV$I
            case $NETDEV in
              ippp*|ppp*|isdn*) ;;
              *)
                echo -n "Shutting down network device $NETDEV"
                ifconfig $NETDEV down || return=$rc_failed
		echo -e "$return"
                ;;
            esac
        done
	;;
    restart|reload)
	$0 stop && $0 stop || return=$rc_failed
	;;
    status)
        for I in $NETCONFIG; do
            eval NETDEV=\$NETDEV$I
            case $NETDEV in
              ippp*|ppp*|isdn*) ;;
              *) ifconfig $NETDEV ;;
            esac
        done
	;;
    probe)
	r=
        for I in $NETCONFIG; do
            eval NETDEV=\$NETDEV$I
            case $NETDEV in
              ippp*|ppp*|isdn*) ;;
              *) probe="`ifconfig $NETDEV 2>&1`"
		 case "$probe" in
		     ${NETDEV}:*unknown*interface*) r=restart ;;
                     ${NETDEV}*) ;;
		 esac
	         ;;
            esac
        done
	test -n "$r" && echo $r
	;;
    *)
    echo "Usage: $0 {start|stop|status|reload|restart}"
    exit 1
esac

test "$return" = "$rc_done" -o "$return" = "$rc_done_up" || exit 1
exit 0
