#! /bin/bash
# Copyright (c) 1996 SuSE GmbH Nuernberg, Germany.  All rights reserved.
#
# Author: Florian La Roche <florian@suse.de>, 1996
#      Werner Fink <werner@suse.de>, 1996
#      Burchard Steinbild <bs@suse.de>, 1996
#
# /sbin/init.d/nfs
#

. /etc/rc.config

nfs=no
while read  where what type options rest  ; do
    case "$where" in
	\#*|"") ;;
	*)  case "$options" in
		*noauto*) ;;
		*)  if test "$type" = "nfs" ; then
			nfs=yes
			break
		    fi ;;
	    esac
    esac
done < /etc/fstab

case `uname -r` in
   0.*|1.*|2.0.*) RPCSTATD="" ;;
   *) test -x /usr/sbin/rpc.kstatd && RPCSTATD=/usr/sbin/rpc.kstatd
esac

return=$rc_done
case "$1" in
    start|reload)
	test "$nfs" = "yes" || exit 0;

	test -n "$RPCSTATD" && startproc $RPCSTATD
	echo -n "Importing Net File System (NFS)"
	# Mount all auto NFS devices (-> nfs(5) and mount(8) )
	#  NFS-Server sometime not reachable during boot phase.
	#  It's sometime usefull to mount NFS devices in
	#  background with an ampersand (&) and a sleep time of
	#  two or more seconds, e.g:
	#  
	#   mount -at nfs &
	#   sleep 2 
	#  
	#  Note: Some people importing the /usr partition.
	#        Therefore we do _NOT_ use an ampersand!
	#
	mount -at nfs || return=$rc_failed
	sleep 1
	#
    	# generate new list of available shared libraries
	#
	ldconfig -X 2>/dev/null
	echo -e "$return"
	;;
    stop)
	test "$nfs" = "yes" && echo -n "Remove Net File System (NFS)"
	#
	# Unmount in background because during long timeouts
	#
	umount -at nfs &
	sleep 2
	test "$nfs" = "yes" && echo -e "$return"
	;;
    restart)
	$0 stop && $0 start || return=$rc_failed
	;;
    status)
	mount -t nfs | while read from x point rest ; do
	    echo -e "$from\033[50G$point"
	done
	;;
    *)
	echo "Usage: $0 {start|stop|status|reload|restart}"
	exit 1
esac

test "$return" = "$rc_done" || exit 1
exit 0
