#! /bin/bash
# Copyright (c) 1996 SuSE GmbH Nuernberg, Germany.  All rights reserved.
#
# Author: Florian La Roche <florian@suse.de>, 1996
#      Werner Fink <werner@suse.de>, 1996
#      Burchard Steinbild <bs@suse.de>, 1996
#
# /sbin/init.d/nfs
#
### BEGIN INIT INFO
# Provides:       nfs
# Required-Start: portmap
# Required-Stop:
# Default-Start:  3 5
# Default-Stop:
# Description:    Imports remote Network File Systems (NFS)
### END INIT INFO

. /etc/rc.status
. /etc/rc.config

nfs=no
while read  where what type options rest  ; do
    case "$where" in
	\#*|"") ;;
	*)  case "$options" in
		*noauto*) ;;
		*)  if test "$type" = "nfs" ; then
			nfs=yes
			break
		    fi ;;
	    esac
    esac
done < /etc/fstab

case `uname -r` in
   0.*|1.*|2.0.*) RPCSTATD="" ; RPCLOCKD="" ;;
   *)
      test -x /usr/sbin/rpc.statd && RPCSTATD=/usr/sbin/rpc.statd
      test -x /usr/sbin/rpc.kstatd && RPCSTATD=/usr/sbin/rpc.kstatd
      test -x /usr/sbin/rpc.lockd && RPCLOCKD=/usr/sbin/rpc.lockd
      test -x /usr/sbin/rpc.klockd && RPCLOCKD=/usr/sbin/rpc.klockd
      ;;
esac

rc_reset
case "$1" in
    start|reload)
	test "$nfs" = "yes" || exit 0;

	test -n "$RPCLOCKD" && startproc $RPCLOCKD
	test -n "$RPCSTATD" && startproc $RPCSTATD
	echo -n "Importing Net File System (NFS)"
	# Mount all auto NFS devices (-> nfs(5) and mount(8) )
	#  NFS-Server sometime not reachable during boot phase.
	#  It's sometime usefull to mount NFS devices in
	#  background with an ampersand (&) and a sleep time of
	#  two or more seconds, e.g:
	#  
	#   mount -at nfs &
	#   sleep 2 
	#  
	#  Note: Some people importing the /usr partition.
	#        Therefore we do _NOT_ use an ampersand!
	#
	mount -at nfs
	rc_status
	sleep 1
	#
    	# generate new list of available shared libraries
	#
	ldconfig -X 2>/dev/null
	rc_status -v
	;;
    stop)
	test "$nfs" = "yes" && echo -n "Remove Net File System (NFS)"
	#
	# Unmount in background because during long timeouts
	#
	umount -at nfs &
	sleep 2
	test "$nfs" = "yes" && rc_status -v
	;;
    restart)
	$0 stop && $0 start
	rc_status
	;;
    status)
	mount -t nfs | while read from x point rest ; do
	    echo -e "$from\033[50G$point"
	done
	;;
    *)
	echo "Usage: $0 {start|stop|status|reload|restart}"
	exit 1
esac
rc_exit
