#! /bin/sh
# Copyright (c) 1996 S.u.S.E. GmbH Fuerth, Germany.  All rights reserved.
#
# Author: Florian La Roche <florian@suse.de>, 1996
#         Werner Fink <werner@suse.de>, 1996
#         Burchard Steinbild <bs@suse.de>, 1997
#
# /sbin/init.d/nfsserver
#

. /etc/rc.config

test "$START_PORTMAP" = no -a "$NFS_SERVER" = no && exit 0

case "$1" in
    start)
    if test "$NFS_SERVER" = yes; then
        echo "Starting NFS server."
        PARAMS=""
        test "$REEXPORT_NFS" = yes && PARAMS="--re-export"
        test -x /usr/sbin/rpc.mountd && /usr/sbin/rpc.mountd $PARAMS
        test -x /usr/sbin/rpc.nfsd && /usr/sbin/rpc.nfsd $PARAMS
        if test "$NFS_SERVER_UGID" = yes; then
            test -x /usr/sbin/rpc.ugidd && /usr/sbin/rpc.ugidd
        fi
    fi
    ;;
    stop)
    if test "$NFS_SERVER" = yes; then
        echo -n "Shutting down NFS server:"
        killproc -TERM /usr/sbin/rpc.mountd
        killproc -TERM /usr/sbin/rpc.nfsd
        killproc -TERM /usr/sbin/rpc.ugidd
        echo
    fi
    ;;
    *)
    echo "Usage: $0 {start|stop}"
    exit 1
esac

exit 0
