#! /bin/sh
# Copyright (c) 1996 S.u.S.E. GmbH Fuerth, Germany.  All rights reserved.
#
# Author: Burchard Steinbild <bs@suse.de>, 1996
#
# /sbin/init.d/pcnfsd
#

. /etc/rc.config

test "$START_PORTMAP" = no -a "$NFS_SERVER" = no && exit 0

case "$1" in
    start)
    if test "$START_PCNFSD" = yes; then
        echo "Starting PCNFS daemon."
        test -x /usr/sbin/rpc.pcnfsd && /usr/sbin/rpc.pcnfsd $PCNFSD_LPSPOOL
    fi
    if test "$START_BWNFSD" = yes; then
        echo "Starting BWNFS daemon."
        test -x /usr/sbin/rpc.bwnfsd && /usr/sbin/rpc.bwnfsd $PCNFSD_LPSPOOL
    fi
    ;;
    stop)
    if test "$START_BWNFSD" = yes; then
        echo -n "Shutting down BWNFS daemon:"
        killproc -TERM /usr/sbin/rpc.bwnfsd
        echo
    fi
    if test "$START_PCNFSD" = yes; then
        echo -n "Shutting down PCNFS daemon:"
        killproc -TERM /usr/sbin/rpc.pcnfsd
        echo
    fi
    ;;
    *)
    echo "Usage: $0 {start|stop}"
    exit 1
esac

exit 0
