#! /bin/sh
# Copyright (c) 1996 SuSE GmbH Nuernberg, Germany.  All rights reserved.
#
# Author: Burchard Steinbild <bs@suse.de>, 1996
#         Werner Fink <werner@suse.de>, 1998,2000
#
# /sbin/init.d/pcnfsd
#
### BEGIN INIT INFO
# Provides:          pcnfsd
# Required-Start:    portmap nfs syslog
# Required-Stop:
# Default-Start:     3 5
# Default-Stop:
# Description:       PC NFS server
### END INIT INFO

. /etc/rc.status
. /etc/rc.config

base=${0##*/}
link=${base#*[SK][0-9][0-9]}

test $link = $base && NFS_SERVER=yes
test "$NFS_SERVER" = yes || exit 0

if test -x /sbin/portmap ; then
    PORTMAP=/sbin/portmap
else
    PORTMAP=/usr/sbin/portmap
fi

rc_reset
return_pc=0
return_bw=0
case "$1" in
    start)
    checkproc $PORTMAP
    if test $? -ne 0 ; then
        echo -n "Starting PCNFS/BWNFS daemon requires portmapper $rc_failed"
        exit 1
    fi
    if test "$START_PCNFSD" = yes -a -x /usr/sbin/rpc.pcnfsd ; then
        echo -n "Starting PCNFS daemon"
        startproc /usr/sbin/rpc.pcnfsd $PCNFSD_LPSPOOL || return_pc=$?
	test $return_pc -eq 0
	rc_status -v -r
    fi
    if test "$START_BWNFSD" = yes -a -x /usr/sbin/rpc.bwnfsd ; then
        echo -n "Starting BWNFS daemon"
        startproc /usr/sbin/rpc.bwnfsd $PCNFSD_LPSPOOL || return_bw=$?
	test $return_bw -eq 0
	rc_status -v -r
    fi
    test $return_pc -eq 0 -a $return_bw -eq 0
    rc_status
    ;;
    stop)
    if test "$START_BWNFSD" = yes -a -x /usr/sbin/rpc.pcnfsd ; then
        echo -n "Shutting down BWNFS daemon"
        killproc -TERM /usr/sbin/rpc.bwnfsd || return_bw=$?
	test $return_bw -eq 0
	rc_status -v -r
    fi
    if test "$START_PCNFSD" = yes -a -x /usr/sbin/rpc.bwnfsd ; then
        echo -n "Shutting down PCNFS daemon"
        killproc -TERM /usr/sbin/rpc.pcnfsd || return_pc=$?
	test $return_pc -eq 0
	rc_status -v -r
    fi
    test $return_pc -eq 0 -a $return_bw -eq 0
    rc_status
    ;;
    restart|reload)
	$0 stop && $0 start
	rc_status
    ;;
    status)
    warning=""
    checkproc $PORTMAP || warning=", no portmapper"
    checkproc /usr/sbin/rpc.bwnfsd && echo "BWNFS up${warning}" || echo "BWNFS down"
    checkproc /usr/sbin/rpc.pcnfsd && echo "PCNFS up${warning}" || echo "PCNFS down"
    ;;
    *)
    echo "Usage: $0 {start|stop|restart|reload}"
    exit 1
esac
rc_exit
