#! /bin/sh
# Copyright (c) 1998 SuSE GmbH Nuernberg, Germany.  All rights reserved.
#
# Author: Burchard Steinbild <bs@suse.de>, 1998
#         originally from Theodore Ts'o <tytso@mit.edu>
#
# /sbin/init.d/random
#
# Script to snapshot random state and reload it at boot time.
#
# Saves and restores system entropy pool for higher quality
# random number generation.
#

. /etc/rc.config

random_seed=/var/run/random-seed

return=$rc_done
case "$1" in
    start)
        echo -n "Initializing random number generator"
        # Carry a random seed from start-up to start-up
        # Load and then save 512 bytes, which is the size of the entropy pool
        if test -f $random_seed ; then
                cat $random_seed > /dev/urandom || return=$rc_failed
        else
                touch $random_seed || return=$rc_failed
        fi
        chmod 600 $random_seed
        dd if=/dev/urandom of=$random_seed count=1 bs=512 2>/dev/null
	test $? -eq 0 || return=$rc_failed
	echo -e "$return"
	;;
    stop)
        # Carry a random seed from shut-down to start-up
        # Save 512 bytes, which is the size of the entropy pool
        echo -n "Saving random seed"
        touch $random_seed || return=$rc_failed
        chmod 600 $random_seed
        dd if=/dev/urandom of=$random_seed count=1 bs=512 2>/dev/null
	test $? -eq 0 || return=$rc_failed
	echo -e "$return"
	;;
    *)
	echo "Usage: $0 {start|stop}"
	exit 1
esac

test "$return" = "$rc_done" || exit 1
exit 0
