#! /bin/sh
# Copyright (c) 1998 S.u.S.E. GmbH Fuerth, Germany.  All rights reserved.
#
# Author: Burchard Steinbild <bs@suse.de>, 1998
#         originally from Theodore Ts'o <tytso@mit.edu>
#
# /sbin/init.d/random
#
# Script to snapshot random state and reload it at boot time.
#
# Saves and restores system entropy pool for higher quality
# random number generation.
#

. /etc/rc.config

random_seed=/var/run/random-seed

case "$1" in
    start)
        echo "Initializing random number generator..."
        # Carry a random seed from start-up to start-up
        # Load and then save 512 bytes, which is the size of the entropy pool
        if [ -f $random_seed ]; then
                cat $random_seed >/dev/urandom
        else
                touch $random_seed
        fi
        chmod 600 $random_seed
        dd if=/dev/urandom of=$random_seed count=1 bs=512 2>/dev/null
	;;
    stop)
        # Carry a random seed from shut-down to start-up
        # Save 512 bytes, which is the size of the entropy pool
        echo "Saving random seed..."
        touch $random_seed
        chmod 600 $random_seed
        dd if=/dev/urandom of=$random_seed count=1 bs=512 2>/dev/null
	;;
    *)
	echo "Usage: $0 {start|stop}"
	exit 1
esac

exit 0
