#! /bin/bash
# Copyright (c) 1996-98 SuSE GmbH Nuernberg, Germany.  All rights reserved.
#
# Author: Florian La Roche <florian@suse.de>, 1996
#	  Werner Fink <werner@suse.de>, 1994,96,98,99
#
# /sbin/init.d/rc   --    The Master Resource Control Script
#
# This file is responsible  for  starting/stopping  services
# when the runlevel changes.  If the action for a particular
# feature in the new run-level is the same as  the action in
# the previous run-level, this script will neither start nor
# stop that feature.
#

# avoid being interrupted by child or keyboard
trap "echo" SIGINT

#
# Get terminal size of standard input of the system console
#
test -z "$CONSOLE" && CONSOLE=/dev/console
set -- $(stty size < $CONSOLE)
  LINES=$1
COLUMNS=$2
export LINES COLUMNS CONSOLE

#
# Configuration
#

. /etc/rc.config

#
# On previous runlevel identical with current runlevel
# do not re-examine current runlevel.
#
test "$PREVLEVEL" = "$RUNLEVEL" && exit 0

#
# This redirects all rc messages during reboot and halt
# to tty1 if the system console is bound on VGA (tty0).
#
if test $COLUMNS -gt 0 ; then
    # VGA
    if test "$RUNLEVEL" = "0" -o "$RUNLEVEL" = "6" ; then
	CONSOLE=/dev/tty1
	test -x /usr/bin/chvt && /usr/bin/chvt 1
    fi
else
    # Serial: columns and lines are not defined
      LINES=24
    COLUMNS=80
fi

#
# Redirect I/O of this script and its childs
#
exec 0<> $CONSOLE 1>&0 2>&0

#
# Set onlcr to avoid staircase effect and do not lock scrolling
#
stty onlcr -ixon 0>&1

#     \033[1m       switch bold on
#     \033[31m      switch red on
#     \033[32m      switch green on
#     \033[33m      switch yellow on
#     \033[m        switch color/bold off
extd="\033[1m"
warn="\033[1m"
norm="\033[m"
stat="\033[71G"

echo -n "Master Resource Control: "
echo -n "previous runlevel: $PREVLEVEL, "
echo -e "switching to runlevel: ${extd}${RUNLEVEL}${norm}"

curdir=/sbin/init.d/rc$RUNLEVEL.d
prevdir=/sbin/init.d/rc$PREVLEVEL.d
rex="[0-9][0-9]"

failed=""
#
# run the KILL scripts of the previous runlevel
#
for i in $prevdir/K*; do
    test -x "$i" || continue

    # don't run the kill script, if the new runlevel has a start script
    start=${i##*/K$rex}
    set -- $curdir/S$rex$start
    test -n "$2" && echo -e "$0: more than one start link\n -- $@"
    test -f $1 && continue

    $i stop || failed="${failed} ${start}"
    echo -n -e "$rc_reset"
done
#
# run the START scripts of the current (new) runlevel
#
for i in $curdir/S*; do
    test -x "$i" || continue

    # don't run start script, if previous runlevel had a kill script
    start=${i##*/S$rex}
    set -- $prevdir/K$rex$start
    test -n "$2" && echo -e "$0: more than one kill link\n -- $@"
    test -f $1 && continue

    $i start || failed="${failed} ${start}"
    echo -n -e "$rc_reset"
done

echo -n "Master Resource Control: "
if test -n "$failed" ; then
    echo
    echo -n "Failed services in runlevel ${RUNLEVEL}:"
    echo -e "${extd}${failed}${norm}"
else
    echo -e "runlevel ${RUNLEVEL} has been ${stat}${warn}reached${norm}"
fi

test -e /etc/issue-SuSE-first-run && {
    cat /etc/issue-SuSE-first-run
    rm -f /etc/issue-SuSE-first-run 2>/dev/null
}

exit 0
