#! /bin/sh
# Copyright (c) 1996 S.u.S.E. GmbH Fuerth, Germany.  All rights reserved.
#
# Author: Burchard Steinbild <bs@suse.de>, 1996
#
# /sbin/init.d/routed
#

. /etc/rc.config

test "$START_ROUTED" = "yes" || exit 0

case "$1" in
    start)
	echo "Starting routed."
	/usr/sbin/routed
    sleep 1
	;;
    stop)
	echo -n "Shutting down routed:"
	killproc -TERM /usr/sbin/routed
	echo
	;;
    *)
	echo "Usage: $0 {start|stop}"
	exit 1
esac

exit 0
