#! /bin/bash
# Copyright (c) 1996 SuSE GmbH Nuernberg, Germany.  All rights reserved.
#
# Author: Burchard Steinbild <bs@suse.de>, 1996
#
# /sbin/init.d/routed
#

. /etc/rc.status
. /etc/rc.config

base=${0##*/}
link=${base#*[SK][0-9][0-9]}

test $link = $base && START_ROUTED=yes
test "$START_ROUTED" = "yes" || exit 0

rc_reset
case "$1" in
    start)
	echo -n "Starting routed"
	startproc /usr/sbin/routed
	rc_status -v
	sleep 1
	;;
    stop)
	echo -n "Shutting down routed"
	killproc -TERM /usr/sbin/routed
	rc_status -v
	;;
    restart|reload)
	$0 stop && $0 start
	rc_status
	;;
    status)
        route -n
	;;
    *)
	echo "Usage: $0 {start|restart|reload|status|stop}"
	exit 1
esac
rc_exit
