#! /bin/sh
# Copyright (c) 1996 SuSE GmbH Nuernberg, Germany.  All rights reserved.
#
# Author: Florian La Roche <florian@suse.de>, 1996
#	  Werner Fink <werner@suse.de>, 1996
#
# /sbin/init.d/rpc
#
### BEGIN INIT INFO
# Provides:       portmap ugidd
# Required-Start: route
# Required-Stop:
# Default-Start:  3 5
# Default-Stop:
# Description:    DARPA port to RPC program number mapper
### END INIT INFO

. /etc/rc.status
. /etc/rc.config

base=${0##*/}
link=${base#*[SK][0-9][0-9]}

test $link = $base && START_PORTMAP=yes
test "$START_PORTMAP" = yes -o "$NFS_SERVER" = yes || exit 0

if test -x /sbin/portmap ; then
    PORTMAP=/sbin/portmap
else
    PORTMAP=/usr/sbin/portmap
fi

rc_reset
case "$1" in
    start)
	checkproc $PORTMAP && {
	    killproc $PORTMAP 2> /dev/null
	    echo -n "Re-"
        }
	echo -n "Starting RPC portmap daemon"
	startproc $PORTMAP
	rc_status
	/bin/sleep 1
        if test "$NFS_SERVER_UGID" = yes; then
	   if test -x /usr/sbin/rpc.ugidd ; then
            startproc /usr/sbin/rpc.ugidd
	    rc_status
           fi
        fi
	rc_status -v
	;;
    stop)
	if test -x /usr/sbin/rpc.ugidd ; then
	  killproc -TERM /usr/sbin/rpc.ugidd
	  rc_status
	fi
	echo -n "Shutting down RPC services"
	killproc -TERM $PORTMAP
	rc_status -v
	;;
    restart|reload)
	$0 stop && $0 start
	rc_status
	;;
    status)
        status="OK"
        if test "$NFS_SERVER_UGID" = yes; then
            checkproc /usr/sbin/rpc.ugidd  || status="rpc.ugidd down"
        fi
	checkproc $PORTMAP && echo "OK" || echo "portmapper down"
	;;
    *)
	echo "Usage: $0 {start|restart|reload|status|stop}"
	exit 1
esac
rc_exit
