#! /bin/sh
# Copyright (c) 1996 S.u.S.E. GmbH Fuerth, Germany.  All rights reserved.
#
# Author: Florian La Roche <florian@suse.de>, 1996
#	  Werner Fink <werner@suse.de>, 1996
#
# /sbin/init.d/rpc
#

. /etc/rc.config

test "$START_PORTMAP" = yes -o "$NFS_SERVER" = yes || exit 0

if test -x /sbin/portmap ; then
    PORTMAP=/sbin/portmap
else
    PORTMAP=/usr/sbin/portmap
fi

case "$1" in
    start)
	echo "Starting RPC portmap daemon."
	eval $PORTMAP
	/bin/sleep 1
	;;
    stop)
	echo -n "Shutting down RPC services:"
	killproc -TERM $PORTMAP
	echo
	;;
    *)
	echo "Usage: $0 {start|stop}"
	exit 1
esac

exit 0
