#! /bin/sh
# Copyright (c) 1998 S.u.S.E. GmbH Fuerth, Germany.  All rights reserved.
#
# Author: Tilman Müller-Gerbes <tmg@suse.de>, 1998
#
# /sbin/init.d/rwhod
#

. /etc/rc.config

test "$START_RWHOD" = yes || exit 0

case "$1" in
    start)
	echo "Starting rwho daemon."
	/usr/sbin/rwhod
	/bin/sleep 1
	;;
    stop)
	echo -n "Shutting down rwho services:"
	killproc -TERM /usr/sbin/rwhod
	echo
	;;
    reload|restart)
	killproc -TERM /usr/sbin/rwhod
	/usr/sbin/rwhod
	/bin/sleep 1
	;;
    *)
	echo "Usage: $0 {start|stop|reload|restart}"
	exit 1
esac

exit 0
