#! /bin/sh
# Copyright (c) 1998 SuSE GmbH Nuernberg, Germany.  All rights reserved.
#
# Author: Tilman Müller-Gerbes <tmg@suse.de>, 1998
#
# /sbin/init.d/rwhod
#
### BEGIN INIT INFO
# Provides:          rwhod
# Required-Start:    portmap nfs syslog
# Required-Stop:
# Default-Start:     3 5
# Default-Stop:
# Description:       The system status server
### END INIT INFO

. /etc/rc.status
. /etc/rc.config

base=${0##*/}
link=${base#*[SK][0-9][0-9]}

test $link = $base && START_RWHOD=yes
test "$START_RWHOD" = yes || exit 0

rc_reset
case "$1" in
    start)
	echo -n "Starting rwho daemon"
	startproc /usr/sbin/rwhod
	rc_status -v
	sleep 1
	;;
    stop)
	echo -n "Shutting down rwho service"
	killproc -TERM /usr/sbin/rwhod
	rc_status -v
	;;
    reload|restart)
	$0 stop && $0 start
	rc_status
	;;
    status)
	checkproc /usr/sbin/rwhod && echo OK || echo No process
	;;
    *)
	echo "Usage: $0 {start|stop|reload|restart|status}"
	exit 1
esac
rc_exit
