#! /bin/sh
# Copyright (c) 1996 S.u.S.E. GmbH Fuerth, Germany.  All rights reserved.
#
# Author: Florian La Roche <florian@suse.de>, 1996
#	  Werner Fink <werner@suse.de>, 1996
#	  Burchard Steinbild <bs@suse.de>, 1996
#
# /sbin/init.d/single
#

. /etc/rc.config

case "$1" in
    start)
        if test -f /etc/default.keytab -a -x /bin/loadkeys; then
                /bin/loadkeys /etc/default.keytab
        fi
        if test -n "$FONT" -a "$FONT" != "YAST_ASK" -a \
                -x /usr/bin/setfont -a -x /usr/bin/loadunimap -a \
                -d /usr/lib/kbd/consolefonts ; then
                /usr/bin/loadunimap
                /usr/bin/setfont $FONT
        fi
        if test -n "$KBD_RATE" -a -n "$KBD_DELAY" -a -x /sbin/kbdrate; then
                /sbin/kbdrate -r $KBD_RATE -d $KBD_DELAY
        fi
        echo "Sending all processes the TERM signal..."
        killall5 -15
        sleep 3
        echo "Sending all processes the KILL signal..."
        killall5 -9
	;;
    stop)
	/sbin/update
	;;
    *)
	echo "Usage: $0 {start|stop}"
	exit 1
esac

exit 0
