#! /bin/sh
# Copyright (c) 1996 S.u.S.E. GmbH Fuerth, Germany.  All rights reserved.
#
# Author: Florian La Roche <florian@suse.de>, 1996
#	  Werner Fink <werner@suse.de>, 1996,98
#	  Burchard Steinbild <bs@suse.de>, 1996
#
# /sbin/init.d/single
#

. /etc/rc.config

case "$1" in
    start)
        if test -n "$FONT" -a "$FONT" != "YAST_ASK" -a \
                -x /usr/bin/setfont -a -d /usr/lib/kbd/consolefonts
        then
                ECHO_RETURN=$rc_done_up
                echo Loading console font $FONT
                /usr/bin/setfont $FONT || ECHO_RETURN=$rc_failed_up
		if test -x /usr/bin/loadunimap -a -d /usr/lib/kbd/consoletrans
		then
			test -n "$TRANSLATION" -a "$TRANSLATION" != "none" && {
			    /usr/bin/loadunimap $TRANSLATION || \
                                ECHO_RETURN=$rc_failed_up
                        }
		else
			/usr/bin/loadunimap || ECHO_RETURN=$rc_failed_up
		fi
                echo -e "$ECHO_RETURN"
        fi
        if test -n "$KBD_RATE" -a -n "$KBD_DELAY" -a -x /sbin/kbdrate; then
                ECHO_RETURN=$rc_done_up
                /sbin/kbdrate -r $KBD_RATE -d $KBD_DELAY || \
                        ECHO_RETURN=$rc_failed_up
                echo -e "$ECHO_RETURN"
        fi
        echo "Sending all processes the TERM signal..."
        killall5 -15
        echo -e "$rc_done_up"
        sleep 3
        echo "Sending all processes the KILL signal..."
        killall5 -9
        echo -e "$rc_done_up"
	;;
    stop)
        ECHO_RETURN=$rc_done
        echo -n "Running update (bdflush) daemon"
        /sbin/update || ECHO_RETURN=$rc_failed
        echo -e "$ECHO_RETURN"
	;;
    *)
	echo "Usage: $0 {start|stop}"
	exit 1
esac

exit 0
