#! /bin/sh
# Copyright (c) 1996 S.u.S.E. GmbH Fuerth, Germany.  All rights reserved.
#
# Author: 
#
# /sbin/init.d/skeleton
#

. /etc/rc.config

case "$1" in
    start)
	echo "Starting foo."
	#/usr/sbin/foo
	;;
    stop)
	echo -n "Shutting down foo:"
	#killproc -TERM /usr/sbin/foo
	echo
	;;
    *)
	echo "Usage: $0 {start|stop}"
	exit 1
esac

exit 0
