#! /bin/bash
# Copyright (c) 1996 S.u.S.E. GmbH Fuerth, Germany.  All rights reserved.
#
# Author: Florian La Roche <florian@suse.de>, 1996
#	  Werner Fink <werner@suse.de>, 1996
#         Martin Scherbaum <maddin@suse.de>, 1997
#         Reinhard Max <max@suse.de>, 1997
#
# /sbin/init.d/xdm
#

. /etc/rc.config

case "$DISPLAYMANAGER" in
    kdm|kde|KDM|KDE) DISPLAYMANAGER=/opt/kde/bin/kdm    ;;
    *)               DISPLAYMANAGER=/usr/X11R6/bin/xdm  ;;
esac
test ! -x "$DISPLAYMANAGER" && DISPLAYMANAGER=/usr/X11R6/bin/xdm

DM=${DISPLAYMANAGER##*/}
PF=/var/lib/xdm/xdm-pid
xdmpid=0

xdmrun ()
{
    test  -s $PF && xdmpid="`cat $PF`"
    pidof -s $DISPLAYMANAGER >/dev/null && return 0
    return 1
}

case "$1" in

    start)
	if xdmrun ; then
	    echo "Warning: $DM is already running"
	    ps cux$xdmpid
	else
	    # After a crash or a kill signal we may have
	    # a wrong owner ship of /dev/console
	    chown root:tty /dev/console /dev/tty0
	    chmod 622      /dev/console /dev/tty0
	    #
	    test -z "$RE" && echo -n "Starting $DM... "
	    $DISPLAYMANAGER
	    test -z "$RE" && echo "Done."
	fi
	;;
    stop)
	if xdmrun ; then
	    killproc /usr/X11R6/bin/xconsole &> /dev/null
	    test -z "$RE" && echo -n "Shutting down $DM... "
	    kill -TERM $xdmpid 
	    test -z "$RE" && echo "Done."
	fi
	;;
    restart|reload)
	export RE=yes
	echo -n "Restarting $DM... "
	$0 stop
	sleep 1
	$0 start
	echo "Done."
	;;
    check)
	echo -n "Checking $DM ... "
	if xdmrun ; then
	    echo "is running"
	    ps cux$xdmpid
	else
	    echo "is NOT running"
	fi
	;;
    *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit 0
