#! /bin/bash
# Copyright (c) 1996 S.u.S.E. GmbH Fuerth, Germany.  All rights reserved.
#
# Author: Florian La Roche <florian@suse.de>, 1996
#	  Werner Fink <werner@suse.de>, 1996,98
#         Martin Scherbaum <maddin@suse.de>, 1997
#         Reinhard Max <max@suse.de>, 1997
#
# /sbin/init.d/xdm
#

. /etc/rc.config

case "$DISPLAYMANAGER" in
    kdm|kde|KDM|KDE) DISPLAYMANAGER=/opt/kde/bin/kdm    ;;
    *)               DISPLAYMANAGER=/usr/X11R6/bin/xdm  ;;
esac
test ! -x "$DISPLAYMANAGER" && DISPLAYMANAGER=/usr/X11R6/bin/xdm

DM=${DISPLAYMANAGER##*/}

return=$rc_done
case "$1" in
    start)
	echo -n "Starting service $DM"
	startproc $DISPLAYMANAGER || return=$rc_failed
	# After a crash or a kill signal we may have
	# a wrong owner ship of /dev/console
	if test "$return" = "$rc_done" ; then
	    chown root:tty /dev/console /dev/tty0
	    chmod 622      /dev/console /dev/tty0
	fi
	echo -e "$return"
	;;
    stop)
	echo -n "Shutting down service $DM"
	killproc -TERM $DISPLAYMANAGER || return=$rc_failed
	echo -e "$return"
	;;
    restart)
	$0 stop && $0 start || return=$rc_failed
	;;
    reload)
	echo -n "Reload service $DM"
	killproc -HUP  $DISPLAYMANAGER || return=$rc_failed
	echo -e "$return"
	;;
    status|check)
	echo -n "Checking for service ${DM}: "
	checkproc $DISPLAYMANAGER && echo "is running" || echo "is NOT running"
	;;
    probe)
	XDMDIR=/usr/X11R6/lib/X11/xdm
	if test $XDMDIR/xdm-config -nt /var/run/xdm.pid -o \
	        $XDMDIR/Xservers   -nt /var/run/xdm.pid
	then
	    echo reload
	fi
	;;
    *)
	echo "Usage: $0 {start|stop|status|restart|reload|probe}"
	exit 1
esac

test "$return" = "$rc_done" || exit 1
exit 0
