#! /bin/sh
# Copyright (c) 1996 S.u.S.E. GmbH Fuerth, Germany.  All rights reserved.
#
# Author: Florian La Roche <florian@suse.de>, 1996
#	  Werner Fink <werner@suse.de>, 1996
#         Martin Scherbaum <maddin@suse.de>, 1997
#         Reinhard Max <max@suse.de>, 1997
#
# /sbin/init.d/xdm
#

. /etc/rc.config

case "$DISPLAYMANAGER" in
    kdm|kde|KDM|KDE)
	DISPLAYMANAGER=/opt/kde/bin/kdm
    ;;
    *)
	DISPLAYMANAGER=/usr/X11R6/bin/xdm
    ;;
esac
if [ ! -x "$DISPLAYMANAGER" ]; then
    DISPLAYMANAGER=/usr/X11R6/bin/xdm
fi

DM=`basename $DISPLAYMANAGER`

case "$1" in

    start)
	test -z "$RE" && echo -n "Starting $DM... "
	$DISPLAYMANAGER
	test -z "$RE" && echo "Done."
	;;

    stop)
	killproc /usr/X11R6/bin/xconsole &> /dev/null
	test -z "$RE" && echo -n "Shutting down $DM... "
	kill -TERM `cat /var/lib/xdm/xdm-pid` 
	test -z "$RE" && echo "Done."
	;;

    restart)
	export RE=yes
	echo -n "Restarting $DM... "
	/sbin/init.d/xdm stop
	sleep 1
	/sbin/init.d/xdm start
	echo "Done."
	;;
    *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit 0
