#! /bin/sh
# Copyright (c) 1996 S.u.S.E. GmbH Fuerth, Germany.  All rights reserved.
#
# Author: Burchard Steinbild <bs@suse.de>, 1998
#
# /sbin/init.d/zzreached
#

case "$1" in
    start)
        ACT_RUNLEVEL=""
        if test -x /sbin/runlevel ; then
            for i in `/sbin/runlevel` ; do
                ACT_RUNLEVEL=$i
            done
        fi
	if test -n "$ACT_RUNLEVEL" ; then
            echo Runlevel $ACT_RUNLEVEL has been reached...
        fi
	;;
    stop)
	;;
    *)
	echo "Usage: $0 {start|stop}"
	exit 1
esac

exit 0
